### ISSUE TITLE
Active indicator alignment problems in Pivot

### ISSUE THREAD

**Issue by abrown313** [microsoft/fast#1900]
When the tabList content is center justified and the window is resized (the width is changed), the active indicator remains anchored at it's current X position even as the X positions of the tabList items change.

The active indicator corrects it's position when another tab is selected, but it does not dynamically correct during resizing.

This is not a problem when the tabList is left aligned and the tabList items have a consistent X offset.

I came across this error when developing on Edge.

**Comment by nicholasrice** [comment]
Thanks @abrown313 - this definitely seems like a bug - Pivot should support this scenario.

**Comment by eljefe223** [comment]
@chrisdholt @nicholasrice I think the only possible solution without changing the underlying tabs component is to store `window.innerWidth` in state and update on resize.

Other option would be to add a render prop to the base tabs component and render the active indicator inside the `TabsList` container that way the active Indicator would track with its parents position. 

Both have drawbacks

**Comment by eljefe223** [comment]
Proposed solution is to use a pseudo element on the `pivot_tabsList` class and position it based on the selected tab. This will keep the active indicator linked to the position of the `tabsList` and work in any layout (centered, left / right aligned tabs). Below is a prototype:

https://codepen.io/eljefe223/pen/mdbrYLN

Since Pivot uses the base component `<Tabs/>` we will need to factor out a pre-styled pivot into an abstract class and layer another pivot on top where we can use `jssStyleSheet` and update the position of the pseudo element inline.

**Comment by chrisdholt** [comment]
closed with #3517

**Comment by chrisdholt** [comment]
closed with #3517
