### ISSUE TITLE
Selects have too much inline end padding

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast#2268]
The chevron of a select trigger is a bit too far from the edge of the select box. If we look at a W10 UWP select, we see about 11px padding on the inline start side, and 6px on the inline end side. Currently we are using 11px on both sides. We generally center the text of a select trigger, meaning the text effectively has 6px above and below it for most selects. We should match this padding on the right side.

Current:
![image](https://user-images.githubusercontent.com/5892363/65538423-2061a980-debc-11e9-8952-3c31a2c120f7.png)
Proposed:
![image](https://user-images.githubusercontent.com/5892363/65538394-10e26080-debc-11e9-86c4-ca52b9e405bb.png)
W10 Select
![image](https://user-images.githubusercontent.com/5892363/65538621-91a15c80-debc-11e9-9f2b-df8c4dbe6b84.png)

**Comment by nicholasrice** [comment]
@bheston can you verify this doesn't match design POR?

**Comment by bheston** [comment]
The design behind this placement is so stacked elements horizontally align:
![image](https://user-images.githubusercontent.com/47367562/65650233-d3b2c700-dfbe-11e9-9f72-97d1c926d71a.png)

This combination is much less common than the same sort of alignment on the left side, but essentially it leave the full 16px for the icon width even though the chevron is smaller.

In FAST all of the horizontal padding is based off of the density control. By default, this is 3x the design unit size, which is where the 12px comes from. It's a more open aesthetic, and is easiest to notice in the 32 x 40 icon only buttons as illustrated above.

I'm hesitant to change this because of the one-off nature of it, but I can see how since the chevron is much smaller than the bounding box, the alignment is a bit off. We may reevaluate the horizontal spacing, as in some cases we've even been using a square 32px button. Sometimes it can be too wide, but overall I think the larger padding has been working.

A concession we could possibly make here, given that we choose to not have the chevron align to other components in the same column, would be to take 4px (fixed, not density based) off the right padding to account for the white space in the glyph bounding box. Let me circulate that idea.

**Comment by chrisdholt** [comment]
Marking this with "needs information" as we wait for feedback from @bheston

**Comment by chrisdholt** [comment]
closed with #3517
