### ISSUE TITLE
Create CLI to easily hook up new components

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#28]
@awentzel commented on [Wed Jan 17 2018](https://github.com/Microsoft/fast/issues/17)

The scope of this task is to create an initial script run by CLI that allows a fluent web component to be easily created.

This script should create files and folders for an initial setup with a working react component in the core framework.  This should be a node script written in TypeScript.

The execution of the script should take a parameter for the library (react, angular), the name of the item (eg. foo) and the level of the item (component or module).

For example, user can use the command line to create a component
```
$ npm run create:component:foo
```

---

@awentzel commented on [Wed Jan 17 2018](https://github.com/Microsoft/fast/issues/17#issuecomment-358474298)

related to #18

**Comment by chrisdholt** [comment]
I think that as it stands now, there is a lot of variation in what is required when creating a component - specifically since it requires working across packages. I think that when created, this task made a lot more sense, but considering our current architecture I think we should close this as obsolete. 

@nicholasrice, @awentzel, @Falkicon any objections?
