### ISSUE TITLE
Re-work the pull request templates to use a directory structure to facilitate multiple templates

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#3250]
# Background

This repository is a mono-repository and as such it includes many projects within it. An example would be that there are component libraries such as `@microsoft/fast-components` and tooling libraries such as `@microsoft/fast-tooling`. These have differences due to their problem scopes and requirements.

## Requirements

To accomodate the range of projects present in this repository there should be individual pull request templates so that a pull request specific to a certain workspace or repository can be chosen.

Refer to the [github documentation](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) on how to create multiple pull request templates.

**Comment by EisenbergEffect** [comment]
I've got a PR up to re-work issue and PR templates but opted not to go with multiple PR templates because there's no way to select them except by using a query string. So, user experience is not so great for that on the GitHub side of things..

Should we close this or but it in "deep freeze" for possibly doing later down the line?

**Comment by janechu** [comment]
I'll place it in deep freeze.

**Comment by janechu** [comment]
Well, actually, changed my mind, I'll close for now and we can re-open should github ever get around to improving that interface.
