### ISSUE TITLE
Remove api-extractor exception from @microsoft/fast-foundation

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#3317]
#3316 implements a change to `packages/web-components/fast-foundation/api-extractor.json` that instructs the `ae-different-release-tags` rule to not fail in CI. This is due to [an issue in api-documenter](https://github.com/microsoft/rushstack/issues/1921) not being able to differentiate exports of the same name. Several components implement a mixin pattern where naming an interface the same as a class is required.

When the api-documenter issue is fixed we can revert the change to our `api-extractor.json` and update the release-tag reference for all relevant exports.

**Comment by Ibrahimmaga** [comment]
api-extractor.json was causing problem in windows environment when I was messing around with prettier:diff to solve windows os validation. This doesn't seems a problem any longer since windows validation is working. But if someone get any exception error, let me know then we will remove the exception.

**Comment by Ibrahimmaga** [comment]
closes #4281
