### ISSUE TITLE
Allow users to change or swap out the elevation ramp 

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#3443]
Currently the elevation ramp is fixed in both the fast-components and the fast-components-msft packages. I think it would be helpful for users to be able to swap out this recipe in favor of their own implementation. This behavior would seem to follow our principle of providing the default out of the box but having a way to fully swap out that portion if desired. I think this is specifically helpful for the fast-components implementation. On the `fast-components-msft` side of things, I think this would be helpful in a scenario where experimentation is desired, or a different ramp is desired for a given form-factor, OS, etc. We typically look to provide this level of flexibility and I think applying the same principle to elevation would be a net-benefit.

**Comment by bheston** [comment]
I like this plan and I've given a lot of thought into how something like this could work for elevation and other styling systems. Elevation has the benefit of being much simpler than other systems (like color) because the inputs and application are more constrained.

I keep coming back to a model where a consumer can override values or functions depending on the level of flexibility needed. For elevation that starts with the `ShadowConfig` definitions. Currently the default style combines two shadows, but other systems use one or three. We gain a lot of flexibility just by having those somewhere configurable like the design system, presumably as a collection of configs that are all merged in the default implementation.

The next level would be to provide a map for `ElevationMultiplier` such that you could redefine what a level means in your design. I think of this similar to the idea of configuring type ramp sizes for headings. That is, ideally I would consume a heading or an elevation by a known name that had meaning I could map to. For instance, in the current system, as a designer I know a dialog should have a 64px elevation, which happens to correspond to e14, which is arbitrary and not possible to override. Even if I could override what e14 means, I might not want to keep dialog and flyout on the same elevation as they are currently implemented. Functionally I'd like to be able to say `dialog elevation = 64` and `flyout elevation = 32` or override those to whatever I want without having to restyle the component. There is probably a way to do this without defining named values for the six current elevated components, but adding semantic names doesn't offend me. Maybe some way to apply the elevation as a design system property directly where needed, so the dialog component would define the value inline and consumers could override it?

The final level would be a complete override of the function used to generate and apply the style value. This might be through the design system, or there might be another place if the design system needs to remain serializable. In this example I would register a new `applyElevation(number)` function that could return whatever css rule it needed to. For instance, to use the new css painting api.

I'm not sure there's a drop-in way to do that without conforming to the function interface, but possibly we could extract the elevation value into another variable and provide access to all defined variables within the elevation implementation so you have complete freedom to do what you need.

**Comment by chrisdholt** [comment]
Closing given #5853
