### ISSUE TITLE
Is there a way to apply styles to child ShadowDOM elements?

### ISSUE THREAD

**Issue by Valks** [microsoft/fast#3548]
I've been going through trying to create my own elements that I wish to use. Part of that journey has lead me to make a toolbar.

Been a Toolbar, I want to change the background of the buttons to be transparent (going for a look like: https://fluentsite.z22.web.core.windows.net/components/toolbar/definition . Now I could create another element, i.e. ToolbarButton that extends Button (and any other controls which need the background removed) and it'll work for my purpose. Still, it feels like something I should be able to do as it's a unique trait of the toolbar.

I'm not sure if it's even possible, but I can't figure it out looking through the documentation and source code on GitHub.

Any advice would be appreciated.

**Comment by EisenbergEffect** [comment]
@Valks I'm happy to provide some thoughts on this...but I'd like to ask a favor of you. Since we just launched FAST recently, we're trying to build up a presence on Stack Overflow. We'd like to handle questions like these there. Would you mind posting a question on Stack Overflow and linking it here? Then I'll hop over to SO and answer for you. How does that sound?

**Comment by Valks** [comment]
I've created an issue: [stack overflow](https://stackoverflow.com/questions/63076287/using-fast-is-there-a-way-to-apply-styles-to-child-shadowdom-elements).

**Comment by EisenbergEffect** [comment]
Apologies for the delay. I posted an answer for you. Hope this helps!
