### ISSUE TITLE
feat: optimize SVGs and script performance for FAST home page

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#3663]
## Original Request
Ensure that all png on the site is switched to SVG and that we have proper asset compression in place.

## Subsequent investigation
Investigate optimizing the performance by placing SVGs on the CDN rather than web packing them into the application.  This will leverage Brotli caching on CDN, concurrent downloading, smaller main JS file size, and less script blocking waiting to download.

Additionally, If we can break out the main.js bundled into a couple of smaller files of roughly ~20Kb I think we can speed up plage load further.  I would expect a 20-30% increase in speed load time after this.

## Solution
TBD

**Comment by EisenbergEffect** [comment]
@awentzel Can you look into compression of the assets? We'd like to get this for the site release on Thursday if possible since it's the one thing that's showing up in the site perf metrics as not ideal.

**Comment by EisenbergEffect** [comment]
@awentzel Here's the perf analysis: https://gtmetrix.com/reports/fast.design/Gc5y0lUo Note that every issue is A except compression which is F.

**Comment by awentzel** [comment]
@EisenbergEffect recommend closing this.  We could squeeze out 1-3% additional reduction, but it comes down to a matter of bytes.  I almost wonder since these files are so slow if it may be better to pull them all from CDN rather than webpack them into our main js file.  We get concurrent loading and reduce js file size have all this embedded as text. Maybe worth a test.

![Screen Shot 2020-08-13 at 7 49 15 AM](https://user-images.githubusercontent.com/16669785/90149666-9a4f8b00-dd39-11ea-978b-beb8dc272df4.png)

**Comment by EisenbergEffect** [comment]
Can we look into putting the SVGs on CDN? Is this something we think we can get into Release 08 or is it going to take longer than that?

**Comment by awentzel** [comment]
@chrisdholt @radium-v to scope and cost.  A few already exist on the CDN, but the background.svg and icons-*.svg I don't believe do.

**Comment by awentzel** [comment]
It looks like one remain ask to close this group.  Migrate all `*.svg` files to CDN.  
![Screen Shot 2020-09-23 at 11 34 28 AM](https://user-images.githubusercontent.com/16669785/94054745-dd693900-fd90-11ea-98b9-3f1ee4bfe377.png)

**Comment by awentzel** [comment]
I don't believe this is an issue any longer. closing.
