### ISSUE TITLE
docs(glossary): Add definitions for "Design System" and "Design Token" to Glossary

### ISSUE THREAD

**Issue by litteredwitherrors** [microsoft/fast#3745]
**What feature are you requesting?**

Add clear definitions of what a "**Design System**" and "**Design Token**" to the FAST website's documentation glossary.

**What would be the benefit of adding this feature?**

These entries would help to bring clarity to each term to reduce confusion. Entries can be referenced throughout the rest of the documentation site.

**Is there any additional context for your request?**
https://github.com/microsoft/fast/issues/3738#issuecomment-676572807

**Comment by nicholasrice** [comment]
I've added Design System to #3747. I *didn't* add Design Token because we don't actually use that term anywhere in code; we refer to Design Tokens as "design system properties".

I do think it could be good to align terminology toward the industry terms. We use #3361 as an opportunity to align to "Design Tokens" in code
