### ISSUE TITLE
[Proposal] Enable Binding in ElementStyles

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#3748]
I had an idea for limited binding in css, so I wanted to share it and see what people thought.

## Example

With this feature in place, you could write the following:

```ts
const styles = css<MyElement>`
  :host {
    padding: ${x => x.padding};
  }
`;

@customElement({
  name: 'my-element',
  styles
})
export class MyElement extends FASTElement {
  @attr size: string = 'medium';

  get padding() {
    switch(this.size) {
      case 'small':
        return '4px';
      case 'medium':
        return '8px';
      case 'large':
        return '16px';
    }
  }
}
```

This allows the same stylesheet to be shared across all instances of `MyElement` but the value of host padding will be dependent on the state of the individual element instance.

## Technical Approach

A naive approach would be to watch bindings and when they change re-evaluate the entire stylesheet by concatenating css and replacing the old styles with the new. While this is the most flexible solution, allowing for unlimited dynamic css generation, it performs very poorly, forcing a full css parse for every change, a new stylesheet instantiation, and a dom update to add/remove sheets.

Alternatively, we could replace the binding expression with a generated, unique CSS variable and then simply update the CSS property value on the host with each change. You would end up with a single stylesheet that looked like this:

```css
:host {
  padding: var(--fast-abc123);
}
```

The limitation is that bindings could only be used in positions where CSS variables are allowed. But, the only work to update is to watch the expression and write the property when it changes.

### Implementation

To implement this, we would enhance the `css` tagged template function so that it allows instances of `Directive` in the content, just like templates do. We would then capture all arrow functions and convert them to a `CSSBindingDirective`. This directive would write a placeholder into the CSS which would be the generated variable name. It would then be used to create a behavior based on the expression and variable name. All of this could use the same `Directive` api we have for templates by implementing `createPlaceholder` and `createBehavior`. Since styles already can have behaviors associated with them, the created behavior is added to the styles. Whatever custom element the styles are added to (either as primary or dynamic styles), the behavior will be activated resulting in property subscription and CSS variable updates.

This approach also enables other CSS directives to be written as well, which could generate CSS and attach behaviors for other purposes than simple css/expression synchronization. One idea would be to change the way our CSS var behaviors are functioning. For example, in our card styles, we have something like this:

```ts
export const CardStyles = css`
    :host {
        ...
        background: ${neutralFillCardRestBehavior.var};
        ...
    }
`.withBehaviors(
    neutralFillCardRestBehavior
);
```

But `neutralFillCardRestBehavior` could be turned into a directive that writes its var out and adds its behavior. Then you would have this:

```ts
export const CardStyles = css`
    :host {
        ...
        background: ${neutralFillCardRest};
        ...
    }
`;
```

And here's how `neutralFillCardRest` could be implemented:

```ts
const neutralFillCardRest = new (class extends Directive implements Behavior {
    public abstract createPlaceholder(index: number): string {
      return 'var(--neutral-fill-card-rest)';
    }

    public abstract createBehavior(target: Node): Behavior {
      return this;
    }

    bind(source: unknown, context: ExecutionContext): void {
      // do behavior stuff when bound
    }

    unbind(source: unknown): void {
      // do behavior stuff when unbound
    }
})();
```

## Downsides

This would require adding new code to `fast-element` but not much. The core abstractions are in place as well as the ability to associate behaviors with styles. We only need to teach the `css` template function about `Directive` and arrow function. We may also need to massage the types for `createPlaceholder` and `createBehavior` a bit.

**Comment by ben-girardet** [comment]
When writing my first component I was surprised that we couldn't use `padding: ${x => x.padding};` inside CSS tags. In fact I tried it without thinking much, just because I did it for the template and wanted to see if this was possible also for CSS.

Therefore from a "coherence" perspective I think it's a great idea.

Another downside I see is the fact that when "inspecting" a component one would see unique css properties such as `var(--fast-abc123)` for each component. Could be a little confusing... But not much.

**Comment by nicholasrice** [comment]
I really like this. I think it would clean up the adaptive color story significantly as well as provide a better mechanism to prevent abuse (and confusion when that abuse breaks component assumptions).

I wonder if this could also be used to make using the Design Tokens from the provider easier as well:

```js
const styles = css<MyElement>`
  :host {
    padding: ${x => x.provider.designUnit};
  }
`;
```

**Comment by chrisdholt** [comment]
I think this could be valuable and solve a few problems such as "badge" which currently looks for a custom map, but a primary concern is hashing of a custom variable here, when we use the pattern, etc. Several partners I'm currently working with have a regular need to flight a variety of changes and possibly the simplest way to do so is to change that variable in some global CSS fashion (stylesheet, style block in head of document, etc). Because this is a directive, nobody has to use it - I think my concern would be more around how *we* choose to use this and how that would affect their ability to accomplish the above. 

Were we not to hash this @EisenbergEffect, you mentioned perf issues...I think that would be potentially prohibitive as well were we to use these in our own patterns.

Considering the below possible implementation, another level of customization would be ensuring that the getter in the example below could be swapped out fully by an implementor. So, if I want to run an A/B test or flight something, I could easily swap out the getter for one instance to provide an alternative styling for MyElement. This would also offset the hashing issue because the hash could still exist, but the result is from my custom getter.

```ts
const styles = css<MyElement>`
  :host {
    padding: ${x => x.padding};
  }
`;

@customElement({
  name: 'my-element',
  styles
})
export class MyElement extends FASTElement {
  @attr size: string = 'medium';

  get padding() {
    switch(this.size) {
      case 'small':
        return '4px';
      case 'medium':
        return '8px';
      case 'large':
        return '16px';
    }
  }
}
```

**Comment by nicholasrice** [comment]
It would be good to make the placeholder portion of this optional. Doing so opens-up use-cases like `forcedColorsStylesheetBehavior` where there isn't a string to return and interpolate into the larger CSS document.

```ts
css`
/* styles */

${forcedColors(css`
    /* forced-colors stylesheet */
`)}
`
```
