### ISSUE TITLE
Tabbed text content when using lists does not align to the text

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3816]
**Describe the bug; what happened?**
On https://www.fast.design/docs/components/tabs if you look at the live editor results for tabs you'll see the following screen shot.

* OS & Device: [e.g. **MacOS**, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft **Edge**, Google Chrome, Apple Safari, Mozilla FireFox]
![Screen Shot 2020-08-28 at 8 05 44 AM](https://user-images.githubusercontent.com/16669785/91583979-d02e6b00-e906-11ea-865e-50afe0371905.png)

**Comment by chrisdholt** [comment]
I think this is ultimately just an instance where the example doesn't work out of the box. From a component level, we shouldn't care or be prescriptive about the content within tabs. I think we can improve or update the example here, but there's no component issue here from my perspective - unless we want to make lightweight anchors/buttons the height of the text rather than the hard coded 40px. If that's the case, we should open a separate issue for that as the implications are larger.

**Comment by chrisdholt** [comment]
Updating the tag here to show "improvement". We need a better example or to include some docs-specific CSS - but there's not an issue with the actual component here.

**Comment by nicholasrice** [comment]
Yea I think the real fix here is to change the example to use `appearance="hypertext"`; I'll submit a PR.
