### ISSUE TITLE
Please take your own medicine :-)

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3853]
As there is not a lot of documentation, examples, blogs etc. the best place to go to understand Fast would be to "inspect" the fast.design site.

But unfortunately you don't always use you own framework or components. For example in the Fast Component Explorer. Some would also see this as a sign that the framework cannot really be used yet which I don't think is true.

For example https://explore.fast.design/components/fast-text-field

![image](https://user-images.githubusercontent.com/42288570/92331225-7996fe80-f075-11ea-9fdb-7e57394a54b5.png)

#### Solution

Use your own framework on your site :-)

**Comment by chrisdholt** [comment]
Hey @MarcSkovMadsen, thanks for the issue :).

The FAST explorer is built on an older version of FAST. We certainly are planning on doing the work to update to the latest web component version rather than the React version. Ultimately, we had to choose between continuing to churn behind the scenes to make everything perfect and in the case of the explorer - rebuild it on Web Components - or get FAST out into the world and take that as a follow-up. 

We are working to continue to improve our documentation as well as our real-world examples. We do appreciate the note and your patience while we work to prioritize some of these things!

If there are specific questions you run into, our Discord community is growing and lots of folks are sharing what they're doing. Wd'd love to have you join us there if you aren't already! 

Adding @EisenbergEffect as FYI, but going to close this as far as an issue standpoint in favor of #3854 which was just created.

**Comment by MarcSkovMadsen** [comment]
Thanks. Good comments.

**Comment by MarcSkovMadsen** [comment]
Just for you info @chrisdholt . It's the same issue at the main https://fast.design site. Maybe there should be a tracker for that as well?

**Comment by chrisdholt** [comment]
@MarcSkovMadsen which part? The homepage is built on fast-element and fast-foundation for the most part. The docs portion is docusaurus, which is a larger transition.

**Comment by MarcSkovMadsen** [comment]
Hi @chrisdholt 

I'f you look at the source. There is all these `site` elements all over the place. Making it hard to get inspiration on what is done.

![image](https://user-images.githubusercontent.com/42288570/92458308-7d399b00-f1c5-11ea-89fa-a19040ae70e4.png)

**Comment by EisenbergEffect** [comment]
@MarcSkovMadsen The `site` elements are site-specific web components built with `fast-element` specifically for this page. They are not mean to be generally reusable but their source is available here if you are interested: https://github.com/microsoft/fast/tree/master/sites/fast-website/src/app/components.
