### ISSUE TITLE
fast-text-area rows not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/fast#3869]
When I explore the `fast-text-area` component in the Component Explorer https://explore.fast.design/components/fast-text-area the component does not change when I change the `rows` attribute.

![fast-text-area](https://user-images.githubusercontent.com/42288570/92563734-50928b80-f278-11ea-93c6-d8b197d20bba.gif)

#### Additional context

It does react when I change the cols attribute.

From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

![image](https://user-images.githubusercontent.com/42288570/92563521-fd203d80-f277-11ea-81a5-938281ba23d8.png)

It's the same when trying to use the `fast-text-area` in an application of mine.

**Comment by janechu** [comment]
Investigated, this looks like a potential component issue, looking for clarification from component implementers for clarification.

**Comment by chrisdholt** [comment]
I see this as somewhat less of a bug and more of a feature request / design update. The reason `cols` work and rows don't is due to the fact that width is set to be dynamic at 100% and height is currently fixed. I agree the fixed height from a design perspective is less than ideal; technically we could update this to set a default cols value and just use that instead, though it would no longer respond to design system values.  I think a better course of action would be to implement #3748. That would allow us to use the design system and the fixed height as a default, but set a dynamic style for the control when the cols attribute is applied.

**Comment by m-akinc** [comment]
I would like to see this implemented.

**Comment by chrisdholt** [comment]
It feels silly looking back and thinking we needed to use the system for this - in fact, what we needed to do was eject from the system. @m-akinc, @MarcSkovMadsen - this is in PR. Thanks for your patience :).
