### ISSUE TITLE
Improvements to maintainability

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast#3875]
When reviewing code quality for churn vs maintainability there are a few outliers receiving F grades over the past week that could use some added attention helping to improve and maintainability and thus overall code quality.

This list is ranked in order of worst offenders which could use refactored for improved quality.
1. [packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts](https://codeclimate.com/github/microsoft/fast/packages/web-components/fast-foundation/src/anchored-region/anchored-region.ts)
2. [sites/fast-component-explorer/app/explorer.tsx](https://codeclimate.com/github/microsoft/fast/sites/fast-component-explorer/app/explorer.tsx)
3. [sites/fast-component-explorer/app/fast-components/config/fast-accordian.ts](https://codeclimate.com/github/microsoft/fast/sites/fast-component-explorer/app/fast-components/configs/fast-accordion.ts)
4. [sites/fast-creator/app/creator.tsx](https://codeclimate.com/github/microsoft/fast/sites/fast-creator/app/creator.tsx)
5. [packages/utilities/fast-colors/src/pixel-box.ts](https://codeclimate.com/github/microsoft/fast/packages/utilities/fast-colors/src/pixel-box.ts)

**Comment by EisenbergEffect** [comment]
I'm not too worried about `anchored-region.ts` as that component has been under heavy development, refactoring, etc., and is not yet released. I think that will stabilize shortly.

Also, no concern over `config/fast-accordion.ts` as that's just some sample data for the explorer.

My guess would be that `creator.tsx` and `explorer.tsx` are just changing due to the incorporation of web components and the work Jane is doing to prep the codebase for further tools investment. @janechu to comment more specifically on those files and whether we need any dedicated time to clean those up. My gut says not to worry too much about those. Also deferring to Jane for `pixel-box.ts` as I'm completely unfamiliar with that.

Based on the screenshot I saw of maintenance and churn, I think we're in a pretty good place overall. It's much better than what I've seen on many other projects I've worked on. So, I'm not too concerned but Jane may have some deeper commentary on areas she's more familiar with.

**Comment by janechu** [comment]
I also agree about `anchored-region.ts`, that is why we decided not to export it from the main `index.ts` and expose it.

Correct also on the `config/fast-accordion.ts`, @awentzel is there any way to mark files as content or configuration so they don't get scanned?

@EisenbergEffect I believe @nicholasrice would know about fast-colors work and therefore `pixel-box.ts`, as for the `creator.tsx` and `explorer.tsx`, in looking at the issues that have been created these are due to the similarities between the both of them, which is why you are seeing the "similar code in 2 locations". I'll assess whether the logic can be consolidated during the move to have a mobile version. It's a good excuse do to the amount of restructuring involved for me to refactor these to the `site-utilities` package if it turns out to be reasonable and I have been doing this piece-meal, hence the existence of `site-utilities` as a resource for all of our sites. It may be more prudent for them to retain their own logic though, so I'll keep everyone updated on that next week.
