### ISSUE TITLE
tabbing stops (or loops back) after second tree-view in storybook fixture in Firefox

### ISSUE THREAD

**Issue by marjonlynch** [microsoft/fast#3882]
Tabbing through tree-view components in the storybook fixture starts looping back to the beginning tree-view after the second tree-view in Firefox (80.0.1 on MacOs). This works fine in Edge.

Example:

1. Run storybook in fast-components
2. Click on tree-view
3. Start tabbing until you see it tabbing through tree-views on the right
4. Observe that after the second tree-view it loops through to the first tree-view on the next tab press

Expect it tab to move to the third, fourth and so on tree-view components until it reaches the bottom

Happens in Firefox (80.0.1) on MacOS

**Comment by chrisdholt** [comment]
Per @marjonlynch - this *is* a Firefox only issue. Works in Edge, Chrome, and Safari.

**Comment by nicholasrice** [comment]
I've been looking into this one but haven't tracked down the source of the issue. I've got a min-repro of the behavior here: https://webcomponents.dev/edit/LHblBiYiXUV2LLbpM1WP

I won't be able to put up a fix prior to Release 12 so pushing this out.

**Comment by nicholasrice** [comment]
I've narrowed down one of the reasons why we're experiencing these focus issues: https://webcomponents.dev/edit/ylwdCUY3qLoP3fpkc1J8

It appears that Chromium and FF both have a behavior where a user cannot tab to an element w/ `[tabindex="0"]` that is *inside* a custom element `[tabindex="-1"]`. This is pretty problematic for the tree-view scenario because FF and Edge *also* has an issue where tab focus gets trapped when the root element (the tree) has `[tabindex="0"]`.

The above link seems like a bug to me, I'll do some research and see if I can find anything on it.
