### ISSUE TITLE
Add new component and its specification: Spin Button

### ISSUE THREAD

**Issue by hardikpthv** [microsoft/fast#3942]
**What feature are you requesting?**
Input Stepper component

**What solution would be ideal for you?**
I am planning to create the specs and later on the component itself.

**What alternatives have you considered?**
None yet.

Is there any additional context for your request?

**Attach screenshots or images add detail to your request:**
To give an idea something like this:
[-][   12  ][+]

- https://www.digitala11y.com/spinbutton-role/
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number
- https://www.w3.org/TR/wai-aria-practices/examples/spinbutton/datepicker-spinbuttons.html
- https://www.w3.org/TR/wai-aria-practices-1.2/#spinbutton

**Comment by hardikpthv** [comment]
@EisenbergEffect, shall we call this component `spin-button` then? Or `input-stepper` I am going to create specs.

**Comment by EisenbergEffect** [comment]
I'm going to defer to @chrisdholt. He leads the team that directly drives the individual components. He likely has a perspective to guide the decision.

**Comment by chrisdholt** [comment]
We typically name things in coordination with the W3C interaction model, a native control if one exists, or to the common control name resolved in the Open UI project. The reason for this is to provide a clear queue for users as to the intent of the control. In this case, because the intent here is to achieve the W3C spin button, I would expect the request to be for "Spin Button".

**Comment by hardikpthv** [comment]
Thanks, @chrisdholt for the information. It's good to know. I will name it then as "Spin Button". :)

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time now.
