### ISSUE TITLE
bug: dialog does not track all possible updates to internal tab queue

### ISSUE THREAD

**Issue by scomea** [microsoft/fast#4038]
The dialog component updates it's list of tabbable elements based on adding/removing child elements but not other cases, like elements having tab index changed programmatically.  This [fix](https://github.com/microsoft/fast/pull/4036) addressed some pressing issues with the dialog tab queue but we should revisit the issue:

- is there a different approach that does not have an external dependency (tabbable)?
- we should be more resilient about catching changes to the tab queue, either by watching for more dom updates or maybe updating the list of tabbable items on each keystroke?

**Comment by tlmii** [comment]
Per discord discussion, I'm adding the details of my scenario that falls under the "... but not other cases, ..." comment in the OP's comment.

In my case, my dialog is hidden initially, so when tabbable is called to determine which children should be in the tabbableElements list, it returns nothing. That's expected behavior with [tabbable](https://github.com/focus-trap/tabbable):

> Any of the above will not be considered tabbable, though, if any of the following are also true about it:
> - has a negative tabindex attribute
> - has a disabled attribute
> - **either the node itself _or an ancestor of it_ is hidden via display: none or visibility: hidden** <---- My issue
> - is nested under a closed \<details\> element (with the exception of the first \<summary\> element)
> - is an <input type="radio"> element and a different radio in its group is checked

But there's no way to get past that with the fast dialog because there's no later request for tabbable elements once the dialog is no longer hidden.

**Comment by scomea** [comment]
we now update the tab queue on each tab keystroke, so this is resolved.
