### ISSUE TITLE
Disabled accordion item is not really disabled

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#4131]
`accordion-item` does not have a disabled attribute. Should we add one? How would it work? There are several things to consider:

The only reference to disabling an item in the W3C  is"If the accordion panel associated with an accordion header is visible, and if the accordion does not permit the panel to be collapsed, the header button element has aria-disabled set to true."

Note: The above is really only referencing the expanded `accordion-item` in `single` expand mode. Since one always needs to be expanded then clicking the item that is expanded wont do anything, so `aria-disabled="true"` should be added.

If an accordion item is `disabled` you can not expand or collapse it. This is fine for the `multi` select scenario, but for `single` select mode what would the expected behavior be? If the disabled `accordion-item` is expanded does that mean the other accordion items can not be?

**Comment by eljefe223** [comment]
My thoughts are to not support a disabled `accordion-item` since there is no reference to that functionality at all.

**Comment by radium-v** [comment]
- if an `accordion-item` is `disabled`, its `expanded` property cannot be changed, meaning:
  - an `accordion-item` that is `disabled` and not expanded cannot be expanded.
  - an `accordion-item` that is `disabled` and expanded cannot be collapsed.
- if an `accordion-item` is `disabled` and `expanded`, would expanding another `accordion-item` in `single` mode collapse the `disabled` item, or prevent the other item from opening, since the `disabled` item is already `expanded` and can't be changed?

Maybe it's possible that a `disabled` property could merely exclude an item from expected `accordion` interaction behaviors and prevent it from changing its initial `expanded` state, but that would have more semantic and accessibility implications that would need to be addressed. For instance, does the content of a disabled item inherit the disabled state as well, or is the state only applied to prevent the ability to expand or collapse the item?

**Comment by eljefe223** [comment]
Should we close this issue? I don't think we should support disabled accordion items as it can create a confusing user experience.

**Comment by SethDonohue** [comment]
Not sure where this was left off, but the disabled accordion item isn't disabled from keyboard navigation.
![disabledaccordionitem](https://user-images.githubusercontent.com/31681651/109062696-19385f80-769d-11eb-861e-06a654603e3d.gif)

It _is_ disabled from click events though.
Should we just removed the disabled property and examples?

I can see a case for an author wanting a panel to not be expandable, maybe until a previous panel does not have required information filled out, etc.

**Comment by SethDonohue** [comment]
Also, if we do keep the disabled attribute it would be good to add a visual showing that the item is disabled, right now there's not visual difference.

**Comment by chrisdholt** [comment]
@eljefe223 I think we need to get this rolling again, let's take another look at what needs to happen to support disabled panels of an accordion.

**Comment by eljefe223** [comment]
This was fixed.
