### ISSUE TITLE
Support Alpine.js

### ISSUE THREAD

**Issue by sirinath** [microsoft/fast#4150]
Please add support for [Alpine.js](https://github.com/alpinejs/alpine)

**Comment by EisenbergEffect** [comment]
@sirinath Can you clarify what you mean by this? Do you mean that we should add an integration doc on how to use fast components inside an Alpine app?

**Comment by sirinath** [comment]
> Can you clarify what you mean by this? 

Add the same level of testing and validation to ensure FAST works with Alpine.js

> Do you mean that we should add an integration doc on how to use FAST components inside an Alpine app?

Yes.

Yes.

**Comment by janechu** [comment]
I'm going to close this in favor of the approach that since we are merely filling gaps in the browser, if a framework doesn't work with our libraries specifically, a bug should be filed against us. Use of `@microsoft/fast-element` should work out of the box and be usable with Alpine.js as what should be written is the same for any HTML element as these are web components. Our docs will be updated in our next major version to take a more minimal approach on integration documentation.
