### ISSUE TITLE
Inconsistency in the styling of the components when focused

### ISSUE THREAD

**Issue by LucSuy** [microsoft/fast#4170]
**Describe the bug; what happened?**
Textfield, Button, Radio, Slider, Switch, TextArea: these get a somewhat thicker grey border when focused. 
Select, Anchor, Button outline on the other hand have a differencing focused styling. (There may be others).
Tabbing the components in a horizontal flex for instance, gives a rather turbulent userexperience.

**What are the steps to reproduce the issue?**
1. Put some of the form components in a horizontal flex
2. Start tabbing between them
3. The differences in styling become clear.

**What behavior did you expect?**
A consistent styling for all form components.

**Screenshot**
![components_having_focus](https://user-images.githubusercontent.com/4997164/101400845-c63ae180-38d1-11eb-9f18-8984115b8141.png)

**In what environment did you see the issue?**

* OS & Device: Windows
* Browser Microsoft Edge 87.0.664.55, Google Chrome 87.0.4280.88

**Comment by chrisdholt** [comment]
Thanks for the issue @LucSuy - definitely a bug. @eljefe223 Can you take a look at this?

**Comment by bheston** [comment]
The intent behind the current design is that in most cases the focus is a 2px (`focusOutlineWidth`) border within the bounds of the control footprint. For instance, on buttons or text inputs, that's a 2px inner border. This replaces a 1px outline (`outlineWidth`) or adds the 2px outline for controls that weren't otherwise outlined. On smaller controls like radios and checkboxes the same 2px treatment is used, but it's offset 2px outside the control to account for those being too small to allow the treatment to be consistently visible. Note that many controls reserve space for the focus border to avoid adjusting padding.
