### ISSUE TITLE
Using a behavior that dynamically loads styles and uses other behaviors seems to not properly append behaviors

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast#4242]
**Describe the bug; what happened?**
We created a behavior that dynamically loads in stylesheets based on a property. We are using this to dynamically load stylesheets based on the `appearance` property for `fast-anchor` and `fast-button`.  The behavior loads in the various styles but not the `behaviors` for the various appearances. Meaning the colors are not loading for the various anchor and button states.

**Comment by nicholasrice** [comment]
Min repro here: https://stackblitz.com/edit/behavior-detachment?file=index.ts

I think there are a few issues going on here:

## Detached Detachment
ElementStyles does not first discern whether the styles are attached to a particular element prior to detaching from it. This causes the styles to filter the adopptedStyleSheets array even if it is not attached, and also to remove any behavior instances used by that stylesheet. I'm thinking we may want to implement some sort of tracking into ElementStyles to surface `ElementStyles.isAttached(element: FASTElement)` and only go through removal of styles if that is true.

## Behaviors can add and remove behaviors 
A behavior can cause additional behaviors to be added or removed. During `Controller.onConnectedCallback()`, behaviors are bound up by iterating over a list of behaviors. If a behavior causes another behavior to be added, it gets pushed into the `Controller.behaviors` array. This happens *during the behavior binding loop*. If a behavior is *removed* by another behavior, the behavior array gets shorter and causes the loop to index a position that does not hold a value anymore, where we then call `bind()` on `undefined`, causing an exception. If a behavior gets added, the array gets longer and the behavior will not get bound. I think we can fix this particular issue by [not caching the behavior array length](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-element/src/controller.ts#L292).

## Behaviors used by multiple ElementStyles
Detachment of *behaviors* associated to an `ElementStyles` when calling `Controller.removeStyles()` does not account for multiple dependencies of the same behavior instance. What we're seeing in the repro above is that while *both* stylesheets depend on the same behavior instance, removing only *one* ElementStyles with the behavior attached unbinds the behavior from the element.

I'm having trouble determining where the bug is regarding this behavior. We *could* implement some tracking system in `Controller.addStyles()` and `Controller.removeStyles()` to only unbind if not other stylesheets are depending on the behavior instance, but the same issue still presents itself with the `Controller.addBehaviors()` and `Controller.removeBehaviors()` interface, which I don't think should conditionally bind / unbind behaviors. A component could un-wittingly remove a behavior used by an `ElementStyles` (or attached through some other means) and this behavior will present itself.

@EisenbergEffect it would be good to get your thoughts on this one.

**Comment by EisenbergEffect** [comment]
The third issue seems the trickiest. We may need to take an approach where, internal to the controller, rather than keeping a list of behaviors, we keep a list of entries that holds a behavior along with a reference count, or something like that. Then only remove the entry and unbind the associated behavior if the count reaches zero. Just off the top of my head idea, but definitely looks like we need some additional bookkeeping involved.

**Comment by nicholasrice** [comment]
We do that type of tracking w/ css custom properties in the DesignSystemProvider, only unregistering and removing the property once the last dependency is removed. Do you think it would be odd if `Contoller.removeBehaviors()` didn't unbind a behavior? Should we introduce a force-remove flag? `removeBehaviors(behaviors: ReadOnlyArray<Behavior>, force = false)`?

**Comment by EisenbergEffect** [comment]
I feel a bit uncomfortable removing without unbinding. That also sort of pushes the burden back on the caller to track more things and know when to unbind or not. We could switch behaviors internally to be a map of behavior to count and then bind/unbind based on that. Would that work?

**Comment by nicholasrice** [comment]
That's what I meant, bad phrasing on my part. I was considering if it would be odd if `Controller.removeBehaviors()` didn't *always* unbind the behavior (would behave as you spec above).

**Comment by EisenbergEffect** [comment]
Ah! Hmm. I think I'm following now. So, the `force` param would say "reduce usage down to zero and unbind" effectively. I think that makes sense.
