### ISSUE TITLE
General Question: Why not use the Dialog Element for the Dialog component?

### ISSUE THREAD

**Issue by Garbee** [microsoft/fast#4444]
HTML provides a built in [dialog element](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element). It allows the browser to automatically handle all of the focus trapping, layering, and as many other accessibility concerns that exist.

I am curious as to why Fast uses a fully custom setup for this component? Looking through #729 I didn't see any support in either direction for using native compared to custom. Nor in the PR for inclusion.

Was this simply a browser support issue at the time rather than including/making a polyfill? Is there something the team sees as incorrect with the native implementation?

**Comment by EisenbergEffect** [comment]
Looks like it's Chromium only right now: https://caniuse.com/dialog Based on looking [here](https://bugs.webkit.org/show_bug.cgi?id=84635) it appears that the webkit work hasn't started yet and that there may be some bugs that are blocking the work. Seems like some of the focus work might even be broken/incorrect in Chromium as well.

@chrisdholt may have some other reasoning for not using the `dialog` element as well.

Note: The polyfill is [here](https://github.com/GoogleChrome/dialog-polyfill) and definitely isn't as seamless as one would like.

**Comment by Garbee** [comment]
Yea, the polyfill isn't *great*. Also I do have some personal issues with the API design. Which are actually detailed on the WICG Discourse [1].

My only concern with not using it where possible is, developers can still use z-indexing to put things on top of the dialog and/or the backdrop. For example, at our company they want toast notifications to be on top rather than using inline form error handling. This is a big accessibility and user experience problem.

What we have right now isn't great, but it does solve a genuine problem and forces correctness.

On the Safari note, it is in their Technical Preview as a developer flag we can turn on. However I haven't dug in to see to what extent they have carried it out thus far.

[1] https://discourse.wicg.io/t/dialog-type-modal-or-else-and-deprecate-showmodal/2305/7

**Comment by chrisdholt** [comment]
Sorry for the long-overdue response @Garbee, the primary reasons are ultimately those noted by @EisenbergEffect and well represented on [MDN Browser Compatability](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#browser_compatibility) as well. I think once this is available across all evergreen browsers we can take a look at supporting it in the following breaking change. We also did recently have some input on supporting the same event model, so that may help some as well.

An alternative if it comes available sooner would be to utilize the new `<popover>` work coming out of Open-UI which may also help solve part of the problem you outlined above about z-index. Closing this for now, but hopefully a few of these changes can land soon!
