### ISSUE TITLE
fix: updating the selected attr in fast-option does not update the value in fast-select

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#4669]
# 🐛 Bug Report

Updating the `selected` attr of a`<fast-option>` contained in a `<fast-select>` should update which option has been selected, currently it would appear that no update occurs.

## 💻 Repro or Code Sample

Example:
```
<fast-select>
    <fast-option>Foo</fast-option>
    <fast-option>Bar</fast-option>
</fast-select>
```

Attempt to add `selected` to the `<fast-option>` containing `"Bar"`.

## 🤔 Expected Behavior

The shown option should now be `"Bar"`.

## 😯 Current Behavior

The shown option remains as `"Foo"`.

## 🔦 Context

This is needed in order to allow an outside control to update the value. If I have a method to clear the stored value, as an example, I should be able to set the value and use `selected` to update the value for `<fast-select>`.

**Comment by rimildeyjsr** [comment]
@janechu @EisenbergEffect - can I work on this?

**Comment by EisenbergEffect** [comment]
Pinging @radium-v since he did the original work on this and has amore knowledge of the status of the work.

**Comment by radium-v** [comment]
The `selected` attribute is internally bound as the `selectedAttribute` property, which is used for setting the `defaultSelected` property. Changing the attribute after the element is connected to the DOM has no effect. Attribute changes can also cause issues for `combobox` and `select` when resetting a form, since the `formResetCallback` uses the `selected` attributes to revert the options to their original state.

There are a few different ways to change the value programmatically:
* Set the `selected` property by binding to `:selected` (instead of `selected`) on the `option`
* Set the `selectedIndex` property on the `select` to match the index of the `option`
* modify the `selectedOptions` property array on the `select` to include the `option`
* change the `value` property on the `select` to match the `value` of the `option`

The first option may be what you're looking for if you're using a `repeat()` directive or other sort of collection loop in a template.

**Comment by rimildeyjsr** [comment]
@radium-v - Thank you for the context! I will get started on this and ask if I have any doubts! 😃

**Comment by radium-v** [comment]
This behavior is no longer reproduceable with the current releases:

* `@microsoft/fast-foundation@2.44.0`
* `@microsoft/fast-components@2.30.1`
