### ISSUE TITLE
feat: add ember integration to fast

### ISSUE THREAD

**Issue by tonedef** [microsoft/fast#4697]
# Ember integration 

Looking at possibly using fast with Ember. Considering LinkedIn's apps are primarily Ember and that LI is part of MS, I think it's a natural fit.

**Comment by tonedef** [comment]
Cool! I'm down to help. Turns out we've got a handful of people here at LI also looking into this. Might be able to get some traction on it soon.

**Comment by nayeem01** [comment]
@tonedef @EisenbergEffect 
hi, there
I would love to help.
Can you guide me a little?
thank you

**Comment by EisenbergEffect** [comment]
For anyone interested in writing the article. You will need to put two things into the PR

1. Add a markdown file here: https://github.com/microsoft/fast/tree/master/packages/web-components/fast-foundation/docs/integrations Name it "ember.md" and follow the same pattern as found in one of the other files in that folder.
2. Add an entry to the table of contents here: https://github.com/microsoft/fast/blob/master/sites/website/sidebars.js#L108 so that it's in alphabetical order.
