### ISSUE TITLE
Provide Workaround Native Styling Css for non binding fast-components

### ISSUE THREAD

**Issue by ameyasubhedar** [microsoft/fast#4782]
There are known issues with model binding various fast-components...
https://github.com/microsoft/fast/issues/4248
https://github.com/microsoft/fast/issues/4727
https://github.com/microsoft/fast-blazor/issues/39
https://github.com/dotnet/aspnetcore/pull/27030

Since they are being discussed with multiple teams and there talks about .NET 6/7 for complete support, I would like to propose a temporary workaround that apps can leverage and have consistent styling for fast components with Blazor buildins.

Blazor Has [Build Ins](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#built-in-form-components) that supports Model Binding, so we just need to apply Fast CSS Style to these built ins.

As a workaround if Fast team can provide Native CSS Style that apps can put in site.css and then apply the style to the razor component of check box by inheriting the build ins then we have model binding behavior from Blazor and Styling from Fast.

Here is an example:

```
Blazor Apps define
Checkbox.razor  inherits from InputCheckbox (This enable the model binding).

// Use native input element and apply fast_checkbox style
<div class"temp-fast-checkbox-style">
     <label>
      <input @ref="_element" type="checkbox" @bind="@CurrentValue" />
             @ChildContent
      </label>
</div>
```

@EisenbergEffect, If Fast team can provide the native CSS class that we can put in temp-fast-checkbox-style, This could be an acceptable workaround till Fast and Blazor teams solves core issues for properties and HTML attributes.

We can use this temporary approach for build in radio, select, number etc... As and when the core issues are fixed apps just need to replace the native input element with fast-component and remove the css styling and everything should work in order.

After removing the workaround the razor component will revert to

Checkbox.razor 
```
<fast-checkbox @ref="_element" @bind-checked="@CurrentValue" @bind-checked:event="onchange" disabled="@Disabled">
    @ChildContent
</fast-checkbox>
```

**Comment by EisenbergEffect** [comment]
Unfortunately, creating light dom styles for components with design system support would be equivalent to a full re-architecture of the entire CSS side of the component model. This is many man months of engineering work most likely, and is unfortunately completely outside of our team's charter. So, I don't think this is a solution that we can provide.

I believe that the real issue here is that Blazor is missing features in support of web components. There needs to be a way to either:

* Bind to a property, since web components can have both attributes and properties.
* OR, at least provide some configuration to Blazor that tells it to use properties instead of attributes for certain element/attribute pairs.

Many front-end frameworks support at least one of these features and have for a number of years. For example, FAST itself supports this. Google's Lit supports it. Angular, Aurelia, and Vue support this as well. Here is a good reference for this: https://custom-elements-everywhere.com/ Notice that the first point under "Handling data" notes whether the library can handle attributes **and** properties.

So, I think the best solution here is to have Blazor support at least one of the above, as this would not just address the issues in FAST but would fix many not-yet-reported problems with web components, which are not part of the HTML standard.

For a short-term fix, there may be some way to use roles, but we have some concerns that that may mess up the accessibility model, which we cannot do. Probably more investigation is needed there.

Another possible fix, would be to have FAST's components deviate from matching the built-ins and instead respond to attribute changes for the `value`. That's probably not a small amount of work as well...and it's runs contrary to our goals of embracing web standards and supporting the OpenUI effort.

**Comment by ameyasubhedar** [comment]
@EisenbergEffect, thanks. Your response makes sense, but the current state is unfortunate because the essential components are not behaving as expected (in the context of model binding), especially for the Microsoft technology stack.

I have been following up with the Blazor team, and it looks like they have no plans to fix this.NET6/.NET7, which is unacceptable for production apps migrating to fast components.

So few questions before I move too much ahead in our evaluation.

- Is the official statement to not use fast-components for asp.net core / Blazor apps till the Blazor supports in .NET6/.NET7 (which is the end of this year or may be next year) because without model binding, I don't see how production apps can receive user inputs and make real use cases.  Am I missing something here, is there any other way to do this ?

- What can the Fast team do to provide a solution in the current .NET 5 timeframe ?

**Comment by EisenbergEffect** [comment]
Closing this as duplicate since we have issue tracked to address the underlying issue.
