### ISSUE TITLE
feat: make tooltips more dynamic and less painful

### ISSUE THREAD

**Issue by UtmostCreator** [microsoft/fast#4826]
# 🙋 Feature Request
Please let me know if I should create tooltip issue for this.

It would be also nice to have it like in bootstrap:

```
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="right" title="Tooltip on right">
  Tooltip on right
</button>
```

By this, I mean having these properties 
`data-toggle="tooltip" data-placement="right" title="Tooltip on right"`

we can set/see that this is a tooltip it has placement right and its text in the title attribute.

As for me, it is not really handy to set id for each element to add a tooltip it adds much more work + id as we know must be unique that only adds complexity

My points:
1. rewrite it so we can use it w/o id attribute (by giving more freedom to the devs);
2. add attributes for tooltip customization.

Attributes which I eager to see:
1. placement (top-start, top, top-end, left-start, left, left-end, right-start, right, right-end, bottom-start, bottom, bottom-end);
2. allow to inject html elements (like `<em> <b> <u> <sub> <sup> <i>`);
3. after a click it will be persistent until you click outside the tooltip (would be nice but not required from the very beginning);
4. font-size control;
5. tooltip color (font), background (color) dynamic as other fast elements;
6. it should work on disabled elements (if the property data-disabled-work="true", some sort of this thing);
7. other attributes which you may like can be found on [bootstrap page](https://getbootstrap.com/docs/4.0/components/tooltips/).

Hope it helps somehow for you to decide on what it would be nice to have.
I am open-minded, so please drop a comment below if you have any questions/suggestions.

## 🤔 Expected Behavior

I need to add new element (fast-tooltip) + I need to make sure the id is unique which is not always possible and handy.

## 😯 Current Behavior

I want to add tooltip to many elements of my UI, and it is extremely inconvenient to add an id and anchor to show it.

## 💁 Possible Solution

Use Some JS to make it possible. (see how it is made in the bootstrap 5)

## 🔦 Context

I have a lot of small icons which must have a tooltip for better comprehension of our clients

## 💻 Examples

```
<any-element data-bs-toggle="tooltip" data-bs-placement="top" title="Tooltip on top">
    Content of an element
</any-element>
```

**Comment by chrisdholt** [comment]
Thanks for the issue @UtmostCreator, I'm happy to have us investigate some improvements to the tooltip ergonomics. With that said, Bootstraps approach doesn't really work given some of our core goals for flexibility, extensibility, use only what you need, etc. Happy to get more into that, but I do think we can take the concepts you like under consideration and figure out how we might be able to provide ergonomics that make it easier to leverage for you.

With that said, I think most everything you're looking for is supported (see below), so if they aren't please let me know so we can help get to the bottom of it!

> 1. placement (top-start, top, top-end, left-start, left, left-end, right-start, right, right-end, bottom-start, bottom, bottom-end);

We have a positioning attribute, which can be used to solve many if not most of these. Are you not finding that in documentation or is there something not working?
> 2. allow to inject html elements (like ```<em> <b> <u> <sub> <sup> <i>```);

I'm able to inject any elements within the tooltip. While they may not be sytled, that's easily accomplished with CSS. Do you have a repro where this is not working? https://explore.fast.design/components/fast-tooltip

> 3. after a click it will be persistent until you click outside the tooltip (would be nice but not required from the very beginning);

We'll need to look at this, for context, we've built the tooltip to meet the requirements from ARIA 1.2 which are outlined here: https://w3c.github.io/aria-practices/#tooltip

> 4. font-size control;

As with all components, the tooltip leverages the type ramp which is defined by the design system. https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/src/tooltip/tooltip.styles.ts

You can change these variables at the design system level, you could change them for the component, or you can pass in your own template as children with your own font styles. I think the control as others offers the same flexibility. Do you have a repro where this isn't working or is this a request for a different type of control over this?

> 5. tooltip color (font), background (color) dynamic as other fast elements;

As with other elements, the tooltip uses a recipe which can be used as-is out of the box and depending on that recipes requirements it should push to meet contrast based on the recipe depending on the situation. Alternatively to this you can always use CSS to change the background and foreground, and in the coming vNext work you can change the recipes themselves and how recipes within the tooltip resolve.

> 6. it should work on disabled elements (if the property data-disabled-work="true", some sort of this thing);
other attributes which you may like can be found on bootstrap page.

I don't think there is anything prohibiting this, this would just be up to you in your implementation. I think based on some of the other feedback that perhaps this is being included here with the hope that you can add a data attribute and a tooltip will show up on any given element. As I mentioned above, I don't think that's inline with the direct goals of the project as it would require that we make a prescriptive API which requires explicit dependencies for each component. Currently, each primitive stands on its own though we strive to create the components in as composable way as possible so that creating these sorts of patterns are easy.

With that said, I'm open to digging in on how we could better enable your scenarios within the tooltip itself or if there is a way that DI could potentially provide a hook which you could opt into (interesting idea). Look forward to your thoughts!

**Comment by KingOfTac** [comment]
Adding onto this since I have a vested interest in tooltips and popups.

Because FAST's core goals are flexibility, extensibility like what Chris said, it should be pretty trivial to create a component that composes `<fast-button>` and `fast-tooltip` to get similar "all-in-one" behavior like Bootstrap.

@chrisdholt on #3, wouldn't it better to look into the `<popup>` control from open-ui for persistent popup-like elements. Personally I think that behavior would be out of scope for a tooltip and more appropriate for a more general use popup element.

**Comment by UtmostCreator** [comment]
@chrisdholt, I do not have any issues except the contain CSS property.
I will try to make a full response to your notes a bit later next week.

> Adding onto this since I have a vested interest in tooltips and popups.
> 
> Because FAST's core goals are flexibility and extensibility like what Chris said, it should be pretty trivial to create a component that composes `<fast-button>` and `<fast-tooltip>` to get similar "all-in-one" behavior like Bootstrap.
> 
> @chrisdholt on 3. wouldn't it better to look into the `<popup>` control from open-ui for persistent popup-like elements. Personally I think that behavior would be out of scope for a tooltip and more appropriate for a more general use popup element.

I cannot disagree with you, yeah; most likely it would be better to make a pop-up element.

**Comment by chrisdholt** [comment]
> Adding onto this since I have a vested interest in tooltips and popups.
> 
> Because FAST's core goals are flexibility and extensibility like what Chris said, it should be pretty trivial to create a component that composes `<fast-button>` and `<fast-tooltip>` to get similar "all-in-one" behavior like Bootstrap.
> 
> @chrisdholt on 3. wouldn't it better to look into the `<popup>` control from open-ui for persistent popup-like elements. Personally I think that behavior would be out of scope for a tooltip and more appropriate for a more general use popup element.

With regard to #3, that's definitely the long term goal. We're working on the Open UI side of things and we work fairly closely with @melanierichards and the Edge team as well so we're definitely eager to see that start to land. With that said, it'll take a bit of time for it to be *fully* useable within the components due to implementors picking it up, but I've been actively thinking through progressive enhancement strategies - especially as popup, select, etc start to get refined. My hope is that we can land something to which allows us to use those elements whenever available to give the best performance and outcomes possible.

**Comment by chrisdholt** [comment]
Closing this for now as I don't believe there is anything further actionable here. For those following the thread, we'll be leveraging the `<popup>` work once available in browsers, which will build on that new standardized element.
