### ISSUE TITLE
feat: Publicly Expose `fixture<T>` in `@microsoft/fast-tooling`

### ISSUE THREAD

**Issue by RehanSaeed** [microsoft/fast#4930]
# 🙋 Feature Request

`@microsoft/fast-tooling` has [`fixture<T>`](https://github.com/microsoft/fast/blob/e85551b6f4c3c79f5c5d8500a0ed2b5988a8def6/packages/tooling/fast-tooling/src/web-components/fixture.ts#L110) which seems like a really useful helper function for tests. It's not currently publicly exposed, can that be changed?

## 🤔 Expected Behavior

Allow us to import [`fixture<T>`](https://github.com/microsoft/fast/blob/e85551b6f4c3c79f5c5d8500a0ed2b5988a8def6/packages/tooling/fast-tooling/src/web-components/fixture.ts#L110).

## 😯 Current Behavior

[`fixture<T>`](https://github.com/microsoft/fast/blob/e85551b6f4c3c79f5c5d8500a0ed2b5988a8def6/packages/tooling/fast-tooling/src/web-components/fixture.ts#L110) is not publicly exposed, so can't import it.

## 💁 Possible Solution

Add it to the `@microsoft/fast-tooling` package.

**Comment by EisenbergEffect** [comment]
@RehanSaeed I've been thinking of creating a new `@micrsofot/fast-testing` package which could container this and other helpers present and future. What do you think of that idea?

There's some trick with circular dependencies. For example, the helpers leverage foundation but are also needed to test foundation. If put into another package, I'm not sure how that would work exactly.

**Comment by RehanSaeed** [comment]
> @RehanSaeed I've been thinking of creating a new @microsoft/fast-testing package which could contain this and other helpers present and future. What do you think of that idea?

Seems like a good idea.

**Comment by rajsite** [comment]
+1 we're trying to leverage it for testing our components as well.

While you're digging in there could the type for [Fixture](https://github.com/microsoft/fast/blob/928d73621c62064992189270a920b2c6d6d9e19e/packages/web-components/fast-foundation/src/test-utilities/fixture.ts#L85) be updated from:

```ts
export interface Fixture<TElement = HTMLElement> {
    // ...
    connect(): Promise<void>;
    disconnect(): Promise<void>;
}
```

to:

```ts
export interface Fixture<TElement = HTMLElement> {
    // ...
    connect: () => Promise<void>;
    disconnect: () => Promise<void>;
}
```

The method type worries the [unbound-method](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/unbound-method.md) eslint rule because it thinks we are destructuring a method and invoking it as a function with the following pattern:

```ts
const { element, connect, disconnect } = await fixture('my-element');
await connect();
```

the workaround to settle eslint's nerves is to invoke it like a method as the type currently suggests:
```ts
const myFixture = await fixture('my-element');
await myFixture.connect();
```

**Comment by EisenbergEffect** [comment]
I should be able to get the types fixed up fairly quickly. Let me do that first and then we can revisit the topic of how to make this more broadly available.

**Comment by EisenbergEffect** [comment]
I've got a PR up to adjust the types: https://github.com/microsoft/fast/pull/5016

**Comment by EisenbergEffect** [comment]
Ok, PR is merged. So, types should be updated in the next release (I believe tonight). 

We're having a discussion on how we extract this for proper use by the community. I think there's a bit more involved due to how this affects package dependencies in our monorepo. For some more details on that, I've written up a brief explanation in the above PR's "Next Steps" section. There's some discussion ongoing. I hope we'll be able to address this but it may take some time due to related monorepo work.

**Comment by rajsite** [comment]
I recently became aware of the [`@open-wc/testing`](https://open-wc.org/docs/testing/testing-package/) package. Interesting to see a take on a web-component agnostic set of test fixture tools. Could be an interesting compare point for what features to put in a separate package / another data point for having a separate package.

**Comment by rajsite** [comment]
We'd still be interested in having the fixture utility available in some form so we can share test patterns with FAST

**Comment by EisenbergEffect** [comment]
Planning this for the set of releases based on FASTElement 2.0.

**Comment by EisenbergEffect** [comment]
PR under review to add this as part of the next major release.

**Comment by rajsite** [comment]
@EisenbergEffect it looks like FASTElement 2 is getting close, will there be -beta or -rc pre-release packages released to test against before the 2.0 release?

**Comment by EisenbergEffect** [comment]
We've got to get together and figure out the logistics of that. I'd like there to be an official beta, rc, etc. yes.

**Comment by rajsite** [comment]
Sounds great! 🎉

**Comment by EisenbergEffect** [comment]
Betas coming very soon 😄
