### ISSUE TITLE
feat: add position support in Select dropdown

### ISSUE THREAD

**Issue by m4thieulavoie** [microsoft/fast#4971]
# 🙋 Feature Request

We would like for the Select component to accept a property allowing to control the dropdown position

## 😯 Current Behavior

No control possible so far

## 💁 Possible Solution

 - Leverage an anchored region in the Select component
 - Add support for right/left `position`

**Comment by m4thieulavoie** [comment]
Did some investigation, copying my results I already pasted in Discord
> okay this is internally handled, and you can actually add the property to the Select, even though it's not documented. However, we would also like to be able to position it to the left/right of its container

**Comment by ben-girardet** [comment]
Should the Select component use an anchored region internally ?

**Comment by m4thieulavoie** [comment]
> Should the Select component use an anchored region internally ?

That was my surprise to realize it's not already the case. Unsure if FAST would like to prioritize this approach however. I see this and adding `left`/`right` to the `position` attribute, and officially expose it.

**Comment by m4thieulavoie** [comment]
As per @scomea in Discord
> Updated anchored region is almost ready to go.  Once that gets in some tooltip updates (auto tracking, viewport lock) will follow quickly.  Looking at flyout for select would be a good thing to do after that. I have a scheme in mind to package up anchored-region configurations so we can name and reuse them in various menu constructs.  https://github.com/microsoft/fast/pull/4931

**Comment by chrisdholt** [comment]
> As per @scomea in Discord
> 
> > Updated anchored region is almost ready to go.  Once that gets in some tooltip updates (auto tracking, viewport lock) will follow quickly.  Looking at flyout for select would be a good thing to do after that. I have a scheme in mind to package up anchored-region configurations so we can name and reuse them in various menu constructs.  #4931

Biggest question here is whether or not this is a breaking change in `foundation` due to wholesale changing the underlying template, parts, etc. Open for discussion, but something to consider for the broader community who may be restyling these.

**Comment by scomea** [comment]
> I also want to be careful on creating reusable patterns without a ton of data or feedback. Abstractions can both help and hurt - we should be thoughtful on when and how we leverage them. Long term, this control will be replaced by the Popup work being incubated in Open-UI which is also something to be aware of.

I'd hope whatever mechanism we come up with to describe menu placement could be generic enough that we could swap the underlying anchored-region configuration for a native popup ruleset - ie. "top", "bottom", "tallest space but prefer bottom", etc..
.

**Comment by chrisdholt** [comment]
> > I also want to be careful on creating reusable patterns without a ton of data or feedback. Abstractions can both help and hurt - we should be thoughtful on when and how we leverage them. Long term, this control will be replaced by the Popup work being incubated in Open-UI which is also something to be aware of.
> 
> I'd hope whatever mechanism we come up with to describe menu placement could be generic enough that we could swap the underlying anchored-region configuration for a native popup ruleset - ie. "top", "bottom", "tallest space but prefer bottom", etc..
> .

For sure - I have the same hope. I think an ideal starting point here would be a spec perhaps? Depending on complexity we could have a crawl => walk => run approach where we move to leveraging Anchored Region (pending breaking change convo), then creating a spec and prototype of an abstraction which can be leveraged, then creating the prod version? I think the priority is feature support, the improvements on how that scales are a different task in my mind currently.

**Comment by ben-girardet** [comment]
I've raised the question because I've seen the anchored region in other components such as menu item and was wondering if anchored region came after select and that could be the reason why it wasn't used for the select popup.

I've created a date picker using a text field and an anchored region for the picker and the end result looks very similar to the select component. I've found this promising and I like when things are reused and bring coherence between different similar components.

But there are many things I'm not aware of, such as the Popup Open-UI that you are talking about. So I happily follow your lead on this topic.

**Comment by chrisdholt** [comment]
> I've raised the question because I've seen the anchored region in other components such as menu item and was wondering if anchored region came after select and that could be the reason why it wasn't used for the select popup.
> 
> I've created a date picker using a text field and an anchored region for the picker and the end result looks very similar to the select component. I've found this promising and I like when things are reused and bring coherence between different similar components.
> 
> But there are many things I'm not aware of, such as the Popup Open-UI that you are talking about. So I happily follow your lead on this topic.

I think the scenario is totally righteous, and we've definitely talked internally about making this change. My primary concern is getting unified support (Anchored Region used) rather than a larger project of an abstraction to leverage across all the components at once. I think that's likely an enhancement beyond this feature work. Just for clarity, my primary point is less a matter of is this a good issue  (It Is!) and more about what we prioritize and how we do the work. I see the feature itself as the priority here as it's lacking, so if it comes to an implementation detail where something is a breaking change, we can move forward temporarily with a non-breaking feature improvement. I'm definitely in agreement on using anchored region, but if it introduces a breaking change, we should plan that update but not block on the feature itself. Hopefully that clarifies my intent above :)
