### ISSUE TITLE
rfc: add support for the CEM Analyzer

### ISSUE THREAD

**Issue by claviska** [microsoft/fast#5020]
# 💬 RFC

The [Custom Elements Manifest Analyzer](https://github.com/open-wc/custom-elements-manifest) is quickly becoming the de facto analyzer for custom element authors, leaning on the emerging [`custom-elements.json`](https://github.com/webcomponents/custom-elements-manifest) standard to automatically and consistently generate useful metadata for custom elements and custom element libraries.

The analyzer currently supports FASTElement through the `--fast` flag when components are defined with the `@customElement` decorator.

```ts
import { FASTElement, customElement, attr } from '@microsoft/fast-element';

@customElement('name-tag')
export class NameTag extends FASTElement {
  @attr greeting: string = 'Hello';

  greetingChanged() {
    this.shadowRoot!.innerHTML = this.greeting;
  }
}
```

The analyzer uses certain heuristics to signal a custom element definition. In this case, the `@customElement` results in a definition that the analyzer understands and reports. This adds an entry in the manifest file, aptly named `custom-elements.json`:

```json
{
  "schemaVersion": "1.0.0",
  "readme": "",
  "modules": [
    {
      "kind": "javascript-module",
      "path": "src/my-element.js",
      "declarations": [
        {
          "kind": "class",
          "description": "",
          "name": "NameTag",
          "members": [
            {
              "kind": "field",
              "name": "greeting",
              "type": {
                "text": "string"
              },
              "default": "'Hello'"
            },
            {
              "kind": "method",
              "name": "greetingChanged"
            }
          ],
          "attributes": [
            {
              "name": "greeting",
              "type": {
                "text": "string"
              },
              "default": "'Hello'",
              "fieldName": "greeting"
            }
          ],
          "superclass": {
            "name": "FASTElement",
            "package": "@microsoft/fast-element"
          },
          "tagName": "name-tag",
          "customElement": true
        }
      ],
      "exports": [
        {
          "kind": "js",
          "name": "NameTag",
          "declaration": {
            "name": "NameTag",
            "module": "src/my-element.js"
          }
        },
        {
          "kind": "custom-element-definition",
          "name": "name-tag",
          "declaration": {
            "name": "NameTag",
            "module": "src/my-element.js"
          }
        }
      ]
    }
  ]
}
```

You can view this example and tweak it in the analyzer's playground [using this link](https://custom-elements-manifest.netlify.app/?source=aW1wb3J0IHsgRkFTVEVsZW1lbnQsIGN1c3RvbUVsZW1lbnQsIGF0dHIgfSBmcm9tICdAbWljcm9zb2Z0L2Zhc3QtZWxlbWVudCc7CgpAY3VzdG9tRWxlbWVudCgnbmFtZS10YWcnKQpleHBvcnQgY2xhc3MgTmFtZVRhZyBleHRlbmRzIEZBU1RFbGVtZW50IHsKICBAYXR0ciBncmVldGluZzogc3RyaW5nID0gJ0hlbGxvJzsKCiAgZ3JlZXRpbmdDaGFuZ2VkKCkgewogICAgdGhpcy5zaGFkb3dSb290IS5pbm5lckhUTUwgPSB0aGlzLmdyZWV0aW5nOwogIH0KfQ%3D%3D&library=fastelement).

With zero effort from the developer, the analyzer is able to identify a custom element, its tag name, attributes, properties, property visibility, methods, etc. With additional JSDoc comments, it can identify a complete API including slots, CSS parts, CSS custom properties, and more.

```ts
import { FASTElement, customElement, attr } from '@microsoft/fast-element';

/**
 * @slot first - The first slot
 * @slot second - The second slot
 * 
 * @csspart part1 - The first part
 * @csspart part2 - The second part
 * 
 * @event some-event - Emitted when something happens.
 */
@customElement('name-tag')
export class NameTag extends FASTElement {
  /** The greeting to announce. */
  @attr greeting: string = 'Hello';

  /** This property can be set to one of two convenient values. */
  someProperty: 'val1' | 'val2' = 'val1';

  /** Changes the greeting to something else. */
  greetingChanged() {
    this.shadowRoot!.innerHTML = this.greeting;
  }
}
```

[View the result in the playground.](https://custom-elements-manifest.netlify.app/?source=aW1wb3J0IHsgRkFTVEVsZW1lbnQsIGN1c3RvbUVsZW1lbnQsIGF0dHIgfSBmcm9tICdAbWljcm9zb2Z0L2Zhc3QtZWxlbWVudCc7CgovKioKICogQHNsb3QgZmlyc3QgLSBUaGUgZmlyc3Qgc2xvdAogKiBAc2xvdCBzZWNvbmQgLSBUaGUgc2Vjb25kIHNsb3QKICogCiAqIEBjc3NwYXJ0IHBhcnQxIC0gVGhlIGZpcnN0IHBhcnQKICogQGNzc3BhcnQgcGFydDIgLSBUaGUgc2Vjb25kIHBhcnQKICogCiAqIEBldmVudCBzb21lLWV2ZW50IC0gRW1pdHRlZCB3aGVuIHNvbWV0aGluZyBoYXBwZW5zLgogKi8KQGN1c3RvbUVsZW1lbnQoJ25hbWUtdGFnJykKZXhwb3J0IGNsYXNzIE5hbWVUYWcgZXh0ZW5kcyBGQVNURWxlbWVudCB7CiAgLyoqIFRoZSBncmVldGluZyB0byBhbm5vdW5jZS4gKi8KICBAYXR0ciBncmVldGluZzogc3RyaW5nID0gJ0hlbGxvJzsKCiAgLyoqIFRoaXMgcHJvcGVydHkgY2FuIGJlIHNldCB0byBvbmUgb2YgdHdvIGNvbnZlbmllbnQgdmFsdWVzLiAqLwogIHNvbWVQcm9wZXJ0eTogJ3ZhbDEnIHwgJ3ZhbDInID0gJ3ZhbDEnOwoKICAvKiogQ2hhbmdlcyB0aGUgZ3JlZXRpbmcgdG8gc29tZXRoaW5nIGVsc2UuICovCiAgZ3JlZXRpbmdDaGFuZ2VkKCkgewogICAgdGhpcy5zaGFkb3dSb290IS5pbm5lckhUTUwgPSB0aGlzLmdyZWV0aW5nOwogIH0KfQ%3D%3D&library=fastelement) Notice how all of the comments carry over into the manifest? 🤩 

## Why is this useful?

Having a custom elements manifest opens up a multitude of possibilities for component authors, all with minimal effort from the developer. Here are some ways `custom-elements.json` is being used _today_ in a variety of projects:

- [Shoelace](https://shoelace.style/) uses the custom elements manifest to power its [entire docs site](https://shoelace.style/dist/custom-elements.json).
- [Tooling exist](https://github.com/open-wc/custom-elements-manifest/tree/master/packages/to-markdown) that will generate docs automatically from nothing more than the manifest.
- [Web Component DevTools](https://chrome.google.com/webstore/detail/web-component-devtools/gdniinfdlmmmjpnhgnkmfpffipenjljo) is a browser extension for Chromium and Firefox that uses the manifest to let you view custom elements and tweak their props much like knobs in Storybook
- Shoelace creates [React-wrapped instances](https://github.com/shoelace-style/react-generator) of its custom elements [using the manifest](https://github.com/shoelace-style/react-generator/blob/master/build.js#L46).
- Using the same strategy, it's possible to create comprehensive wrappers for other frameworks, including Blazor.

Here are some additional ways the custom elements manifest might be useful ([source](https://dev.to/open-wc/introducing-custom-elements-manifest-gkk)):

- Tooling that can compare manifests and identify potential breaking changes between versions
- More accurate code completion in editors
- More accurate custom element linting

## What's the problem?

By now, I hope I've sold you on the importance of `custom-elements.json` and you're probably thinking, "if it already supports FAST, what's the problem?" 🤔 

The problem is when we take advantage of FAST to create a design system from scratch. Consider this code:

```ts
import { fastButton, provideFASTDesignSystem } from "@microsoft/fast-components";

provideFASTDesignSystem()
  .withPrefix('faster')
  .register(fastButton());
```

That's all it takes to register a design system with a FAST button called `<faster-button>`. As you can see, FAST provides a way to register custom elements with arbitrary prefixes very easily. This is really convenient for devs, but difficult for the CEM Analyzer to understand.

I appreciate that this issue isn't really FAST's responsibility, and it's likely not an easy one to solve. However, I'm opening it up with hopes that a dialog between FAST and the team behind the CEM Analyzer can lead to a solution.

As an avid user of both tools, I'd like to connect @thepassle and @bennypowers (who have put in an amazing effort on the CEM Analyzer) with @chrisdholt and @EisenbergEffect (who have done amazing things with FAST).

## Example Repo

To ease the burden of testing things out, I've providing a sample repo that runs the analyzer on a minimal FAST implementation.

https://github.com/claviska/fast-cem-analyzer

Instructions for running it are in the [README](https://github.com/claviska/fast-cem-analyzer#readme). The generated [custom-elements.json](https://github.com/claviska/fast-cem-analyzer/blob/master/custom-elements.json) file exists in the root.

**Comment by EisenbergEffect** [comment]
We're totally onboard with `custom-elements.json` and would love to use the CEM analyzer if possible. I *think* that we would want to have the analyzer just analyze the `fast-foundation` classes. That's where the attributes and other members are, as well as the events. We could add docs annotations for slots and css parts. That's technically owned by the template, which is elsewhere, but I think it would be reasonable, at least for us, to put the annotations on the class, since that's really part of the contract anyway. So, that leaves us with two initial problems to solve:

* CEM Analyzer would need to understand our `FoundationElement` base class (in addition to `FASTElement`)
* We probably need some sort of hook to provide the name, since that is no longer declared in the decorator

The first bullet I'm going to guess is pretty straight forward since a similar pattern has already been implemented. The second one is more tricky. Is there a custom docs tag that we could use to provide the default name? How to handle the Fluent components then? They have the same base name but different prefixes. And in some cases they inherit the foundation classes and add additional attributes.

@claviska What is your personal main scenario to solve? For example, is it to help us have better documentation for our components? Or is it to enable folks who are creating custom design system to be able to easily generate docs for components they base on `fast-foundation`?

**Comment by thepassle** [comment]
Looking at the example repo, the issue doesnt necessarily seem to be the syntax for registering the element:
```js
provideFASTDesignSystem()
  .withPrefix('faster')
  .register(fastButton());
```

We can write a [custom plugin](https://custom-elements-manifest.open-wc.org/analyzer/plugins/intro/) to support that syntax, should be no problem.

The bigger problem is following bare module specifiers, which currently the analyzer doesn't really support. I guess you could work around this with a custom plugin if `'@microsoft/fast-components'` shipped a CEM for the components in that package; if (for example) `fastButton()` gets registered by a consumer of `@microsoft/fast-components`, you could lookup the metadata for `fastButton` in the CEM under `node_modules/@microsoft/fast-components`. (note that if `@microsoft/fast-components` uses export maps, the CEM should also be shipped in the export map, otherwise tools will have no way of reaching the CEM 🙃 )

This would probably also mean the FAST plugin wont be able to run in the browser, though, because you'll have to do resolving of node_modules etc. That might not be a problem for the FAST plugin, but for the analyzer itself, it is a goal to work in the browser.

**Comment by claviska** [comment]
@EisenbergEffect,

> What is your personal main scenario to solve? For example, is it to help us have better documentation for our components? Or is it to enable folks who are creating custom design system to be able to easily generate docs for components they base on fast-foundation?

In general, I'd like to see the analyzer work with all possible instantiations of FAST components.

However, my team's current pain point is working to implement Fluent web components using the aforementioned technique. For consistency with other components, we may have to trick the analyzer into seeing the component and manually add JSDoc comments for attributes, properties, etc., which is less than optimal.

Here's a rough example:

```ts
//
// This is all we technically need to instantiate
//

import { provideFASTDesignSystem } from "@microsoft/fast-components";
import { fluentButton } from '@fluentui/web-components';

const button = fluentButton();

provideFASTDesignSystem()
  .withPrefix('my')
  .register(button);

//
// The rest of this tricks the analyzer into reporting the component
//

/**
 * @since 1.3
 * @status experimental
 *
 * @tag my-button
 *
 * @attr {accent | lightweight | neutral | outline | stealth} appearance - The button's visual treatment
 * @attr {boolean} autofocus - Determines if the element should receive document focus on page load
 * @attr {boolean} disabled - Sets the disabled state of the button
 * @attr {string} form - The ID of a form to associate the element to
 * @attr {string} formaction - The HTML formaction attribute of the button
 * @attr {string} formenctype - The HTML formenctype attribute of the button
 * @attr {post | get} formmethod - The HTML formmethod attribute of the button
 * @attr {boolean} formnovalidate - The HTML formnovalidate attribute of the button
 * @attr {_self | _blank | _parent | _top} formtarget - The HTML formtarget attribute of the button
 * @attr {string} name - The HTML name attribute of the button
 * @attr {submit | reset | button} type - The HTML type attribute of the button
 * @attr {string} value - The HTML value attribute of the button
 *
 * @slot - The content of the anchor
 * @slot start - Contents of the start slot are positioned before the button content
 * @slot end - Contents of the end slot are positioned after the button content
 */
 export default class Button extends component.type {}
```

The problem here is that we're hardcoding important API info that we would normally get for free through the analyzer, and as FAST and Fluent components evolve, we'll need to manually keep things in sync for every component. I might explore adding a custom plugin to the analyzer that leans on `fast-components-msft.api.json` — at a glance, it looks like most of the API data we're interested in exists there.

Regardless, this isn't a blocker for my team, it's just a really nice to have and I think the community will benefit greatly if things Just Worked™ with minimal effort. 😄 

---

@thepassle,

> The bigger problem is following bare module specifiers, which currently the analyzer doesn't really support. I guess you could work around this with a custom plugin if '@microsoft/fast-components' shipped a CEM for the components in that package; if (for example) fastButton() gets registered by a consumer of @microsoft/fast-components, you could lookup the metadata for fastButton in the CEM under node_modules/@microsoft/fast-components.

Thanks for your insight here. I may have to do something like this to get data from `fast-components-msft.api.json` and transfer them into the manifest. Not ideal, but better than manually adding the API as JSDoc comments.

Back to the original problem — is there anything we can do that would make it easier for the analyzer to follow components when instantiated this way? 🤔

**Comment by thepassle** [comment]
> Back to the original problem — is there anything we can do that would make it easier for the analyzer to follow components when instantiated this way? 🤔

Im confused 🙈 did my reply not answer the original problem? Can you elaborate on what you mean? I might be misunderstanding 🙂

**Comment by claviska** [comment]
No worries! If I understand correctly — and it's totally possible I've borked it in my own head — I believe you're suggesting that FAST Components would have to ship a CEM that we can merge into the requiring library's CEM using a plugin.

My question is, is there anything the FAST team can potentially do to help the analyzer discover components created with this syntax:

```ts
import { fastButton, provideFASTDesignSystem } from "@microsoft/fast-components";

provideFASTDesignSystem()
  .withPrefix('faster')
  .register(fastButton());  // <faster-button> is now registered
```

That way, we don't have to rely on them shipping a CEM of their own.

I'm just trying to find the best path forward with very little knowledge of how the analyzer actually works. If the answer is generating a CEM then that's OK, but if there's something that can be changed code-wise (or perhaps with custom `@tags`) to trigger or tip off the analyzer to recognize it, it might be worth exploring. 😅

**Comment by thepassle** [comment]
The easiest and most clear-cut way is for `'@microsoft/fast-components'` to ship a CEM. Then create a custom plugin to detect the `.register` syntax, and pick up `'@microsoft/fast-components'`'s CEM to get the metadata for that component.

Currently, the analyzer doesnt 'follow' bare module specifiers. The analyzer consists of two parts: the CLI, and the `create` function (which analyzes and creates the CEM). The CLI takes globs, reads the files from the filesystem, turns them into TypeScript sourcefiles, and passes the sourcefiles to the `create` function. We only know if a package makes use of third-party components when we analyze them, which is when the TypeScript sourcefiles have already been created. I may be able to create/append more TypeScript sourcefiles 'on the go'(/while analyzing) and just add them to the array of to-be-analyzed-sourcefiles, but it's tricky, because which bare module specifiers do you analyze? You dont want all of lodash to end up in your CEM, for example.

Maybe it could be a config option to provide an array of bare module specifiers to follow in the config, e.g.:
```js
export default {
  globs: ['src/**/*.{js,ts}'],
  followSpecifiers: ['@microsoft/fast-components', '@lion/button'],
  plugins: [
    /** myAwesomePlugin() */
  ],
}
```

Sorry if this got a bit ramble-y, trying to think out loud a bit here. I'll try to experiment some with this idea this week and see if I can cook something up.

**Comment by bennypowers** [comment]
> Maybe it could be a config option to provide an array of bare module specifiers to follow in the config, e.g.:
WDYT of using an import map?

**Comment by EisenbergEffect** [comment]
@williamw2 Here's another issue I found that's related to what you are working on.
