### ISSUE TITLE
Remove the accent color picker from the top bar of Creator

### ISSUE THREAD

**Issue by janechu** [microsoft/fast#5069]
# Description

The accent color is no longer a top level item for the default fluent web components and should not be top level next to the LTR/RTL control and the theme control.

## Requirements

- Confer with design that this should be the case
- Remove the control from the top bar

**Comment by williamw2** [comment]
The idea to remove the control from the top bar came about because it did not change the appearance of Fluent components. However, after consulting with design this may be a bug in the Fluent library or with the Creator's implementation.  @chrisdholt is investigating. In the mean time we will leave this issue open until investigations are complete.

**Comment by janechu** [comment]
Closing via #5086 as this enables the color picker for fluent web components and the design consensus is that it is a top level item, with theme and RTL switching.
