### ISSUE TITLE
fix: remove margin from host elements

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#5407]
# 🐛 Bug Report

It recently was brought up in Discord that certain elements seem to have margin applied to the host element; while reviewing changes to the visual refresh, I found this to be the case.

## 💻 Repro or Code Sample

Switch and RadioGroup are two examples at the outset which apply margin to the host element.

## 🤔 Expected Behavior

Margin is used to provide space between things or relative to things within a given layout or context. We apply margin to the switch when a label is applied in the shadow root, but the radio itself shouldn't have margin. Consider the implications of every button having 4px top margin, or left margin, etc. In every scenario you want to use a component, you end up needing to remove this. 

Components should not apply margin arbitrarily as that should be applied contextual as its application varies based on the given context.

## 😯 Current Behavior

Margin is applied to the host element of various controls.

## 💁 Possible Solution

Remove it :)

## 🔦 Context

This issue affects nearly any use case where a user wants to position an element as they need to remove or alter the margin in order to accomplish their goals. We should stay out of users ways and provide a primitive that doesn't make assumptions about the context it is going into.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* Version [e.g. 1.8.0]

**Comment by bheston** [comment]
For `Switch` it looks like this is because the status message part has margin to separate it from the switch part, but if the status message is empty the part still shows and takes space. Seems like we need handling to identify that the message is empty and hide the part, or another way to handle the layout here.

**Comment by chrisdholt** [comment]
> For `Switch` it looks like this is because the status message part has margin to separate it from the switch part, but if the status message is empty the part still shows and takes space. Seems like we need handling to identify that the message is empty and hide the part, or another way to handle the layout here.

Not looking at the code, but assuming that’s a named slot, if the message exists perhaps it can be applied there. Being a named slot would require an element rather than plain text.

**Comment by bheston** [comment]
The root of this bug as far as I know is the horizontal margin on `switch` resulting from an empty status message:
![image](https://user-images.githubusercontent.com/47367562/142666428-31db090a-da38-4349-b4b0-d6d9edb85560.png)

It's clear that we should not have the horizontal margin per your comments above. The bug is written generally though about removing it everywhere. I do think there are reasons for keeping the top and bottom margin on smaller controls like this though (also visible in the screenshot above). This is a sensible default because it encourages proper default layout and spacing regardless of container layout. For instance, a switch, checkbox, or radio should be centered vertically when next to a text input. This is possible in flex layout, but would not be the default configuration. In that model the margin doesn't cause any problems. In a vertical layout it's also by-design to have increased footprint for these controls to maintain the cadence between elements. If we don't include the default layout to support that, features like adaptive density actually become harder to implement consistently because then every consumer needs to manually set the appropriate adaptive configuration value.

This is the height the other component frameworks are using which may also help if we were to offer an alternate focus style:
![image](https://user-images.githubusercontent.com/47367562/142667818-967f887a-3bcc-4c25-b6de-1b52fdd92576.png)
(from WinUI)

If this is applied to the root it's easy to remove when needed, but that is likely the edge case for these controls.

**Comment by chrisdholt** [comment]
I think "proper layout" is an assumption here. This just came up in discord where a user was curious why there wasn't margin around elements by default, but if you notice their layout, it's not "proper" with default top margin on the button here: ![image](https://user-images.githubusercontent.com/13071055/142676109-e5a718fc-10be-4f5d-939c-930e6ffe56fe.png)

Layouts may or may not be horizontal or vertical. Buttons may be used in a variety of scenarios. The problem with saying these are sensible defaults is that they fundamentally make assumptions about the context they are being used in. From an engineering principles standpoint, I firmly believe that components should be isolated to what they care about. They care about _their_ presentation and as component authors we should not make assumptions about their layout or context.

> If we don't include the default layout to support that, features like adaptive density actually become harder to implement consistently because then every consumer needs to manually set the appropriate adaptive configuration value.

If we implement adaptive density and support space around components it becomes harder and less intuitive to remove that space. I think a minimum bar for adaptive density is having helpers to apply space around things. That enables that scenario. I don't think its a requirement that components make assumptions about their context.

**Comment by chrisdholt** [comment]
An argument could be made that removes this right now would be breaking. In that case, I propose we remove all margin on controls as part of the visual refresh to avoid causing issues with current implementations. But this is a change that needs to be made. We shouldn't hoist layout concepts or assumptions into primitives. If the concern is how others apply concepts such as adaptive density, we should come up with a solution that can scale. We'll need to do that anyway as any sensible default wouldn't handle all scenarios anyways.

**Comment by bheston** [comment]
I've seen that button and text box case you posted, but that's not margin. We should 100% fix that. I don't recall if I ever figured out a good way, but I'm glad we're looking at it now.

The _only_ controls I propose we leave as-is are the small ones where the assumption that they have the footprint of any other control is safer. Of course, the downside of that is that there is no way to globally apply 4px or 8px padding around all controls in a container, but that's probably better done with `gap` than margin anyway. Perhaps that's an argument for an _actual_ 32px height on smaller controls, using the focus treatment I included above as an example and basis for the footprint.

**Comment by chrisdholt** [comment]
> I've seen that button and text box case you posted, but that's not margin. We should 100% fix that. I don't recall if I ever figured out a good way, but I'm glad we're looking at it now.
> 
> The _only_ controls I propose we leave as-is are the small ones where the assumption that they have the footprint of any other control is safer. Of course, the downside of that is that there is no way to globally apply 4px or 8px padding around all controls in a container, but that's probably better done with `gap` than margin anyway. Perhaps that's an argument for an _actual_ 32px height on smaller controls, using the focus treatment I included above as an example and basis for the footprint.

Sure, I saw the note and it's odd and we should fix - but I think it illustrates the problem of having margin on top. Even if it's not margin, I can create a repro with those which have it to illustrate the same issue. What components _should_ have the space around them in your mind? What's the story there and why is it intuitive for all layouts?

**Comment by Falkicon** [comment]
I would rather see no margin on any components ever. Past experience shows, as soon as you make a reason to add margin ("it is usually used like this") Someone needs to use it in some other way and they have to remove the margin. Instead, I would prefer to see some system/utility/token method for developers to be able to add margins systematically and in a way that works well with Adaptive UI/Density. "Adaptive Spacing"?

**Comment by bheston** [comment]
The button issue isn't a good comparison as it illustrates a different layout issue. If the checkbox had space built into it it would at least be apparent where that was coming from instead of with the button.

Maybe "margin" is the wrong word, but the control should have size built into it for spacing as well as touch target size. 

Here's a comparison across design systems. Discord adds a backplate, but it demonstrates that they think of the footprint the same as text inputs. Material uses the space for focus treatment. If we want to be able to support other or future focus treatments we need space for that. Again, margin may not be the right place for that though. Lastly, back to WinUI, which we probably want to be closer to than anything else. Consider the footprint however we get there.

![image](https://user-images.githubusercontent.com/47367562/142702670-50526ed1-366c-4d02-9f52-e62ff0b71ce4.png)
(magenta is the control bounds, green is common spacing)

We'll get into spacing with density, but it's not going to be easy to solve for mixed cases like this. For example, controls should layout like this:
![image](https://user-images.githubusercontent.com/47367562/142703118-45f68bc4-c51f-4edf-a13c-b74347e9955a.png)

The text fields have 8px between, the radios have the same 8px between, and the hopefully fictious example after that still has 8px.

If it helps, let's move the margin to internal padding and change the focus treatment while we're at it.

As far as the rule, it's for checkbox, radio, and switch only. Anything smaller than standard single-unit height. We don't need special handling for larger components like text area.

**Comment by bheston** [comment]
I meant to mention that considering the footprint size of the control isn't much different from some other components that may or may not have a backplate or visual representation of their boundary, like Tabs. Whether tabs have a background or not, they still take the standard height.

**Comment by chrisdholt** [comment]
I'm still not seeing a good argument here for why controls should make assumptions about their layout. Given your examples, Material reserves that space because of the hover treatment, illustrated above - that's a different consideration. If our components required a broader hover treatment, their bounds would _grow_ - that's a fundamentally different argument than adding margin. What I see above is you articulating what the bounds of the control are, which is where we are aligned - controls should not make assumptions about their boundaries.

If the proposal here is to move the space within the control, you're more than happy to create a feature request to do so, but that will bring with it a new set of explorations and concerns - removing that becomes a larger hassle if we move it to the shadow DOM. The better approach is to treat it as it is - contextually. If the control _requires_ a larger footprint because the hover state extends beyond the existing visual bounds, that is one thing, but the argument here is whether controls should reserve space above and below, making assumptions about their layout, what precedes it and what comes after it in the DOM. That's 100% the concern. The same concern exists w/ z-index as it relates to stacking context. All of that is massively contextual and when we make assumptions about how controls compose at the lowest level, we add another layer of opinion that a user must overcome to use it in _their_ context.

Layout is contextual, margin relates to layout. The compositions you are showing above are _layouts_ and compositions. For form controls, we're looking at adding a "fast-field" ergonomic which could address the layout and spacing considerations you have, enabling and reserving space for error states, etc...but that should not be included in the lowest level primitives. 

I don't see us discussing the footprint here, we're discussing relationship to other controls. Footprint is different. Nothing about the hover state, focus state, etc. requires space to be reserved. The argument for tabs is reasonable because it's a block level element and it shouldn't jump, but saying that all tabs should have a min-height of 200px is different than saying the tabs control should have top margin of 8px and bottom margin of 4px. That is a fundamentally different argument. One is about the control itself and the other is about it's relationship to other controls. If we want to do something where we create a relationship between controls we can do so - but I don't think it's fair to compare these two as the same argument as they are not.

**Comment by Falkicon** [comment]
Yes, in the case of controls like Radio and Checkboxes, if your extending the click area, then I think of that inside of the component. Same argument might be for a stealth button, where you only see the button on hover. The extra space around the text when not hovered is not extra margin, it is just a component that does not have visual borders.

**Comment by chrisdholt** [comment]
> Yes, in the case of controls like Radio and Checkboxes, if your extending the click area, then I think of that inside of the component. Same argument might be for a stealth button, where you only see the button on hover. The extra space around the text when not hovered is not extra margin, it is just a component that does not have visual borders.

In this case as well, I'd argue that the extension of form controls would be handled by something like `form-field` which can better tie the control to a label, handle the additional space for error messages, etc...it's just all contextual. The primitive itself should be contained within it's borders whether visible or not, as is the case with a stealth button. What we shouldn't do is have the control apply margin in expectation of a future potential relationship with another control, etc.

**Comment by Falkicon** [comment]
+1

**Comment by bheston** [comment]
I'd be more fine with moving this into something like fast-field if it already existed. Since we've had the space before, it's going to collapse layouts if they are not updated and this change is pushed. I'm fine with it going in the FAST visual update as that _should_ be considered a visual breaking change. I still think without better form layout this will make it easier to create less-desirable layouts, but am less concerned about that for the FAST design.

I didn't see if you proposed the same in Fluent UI, but _until_ we have something to better support form layout there I am concerned with removing any margin. In Fluent there _is_ an opinion about the spacing those controls take, and even if margin is not the best place for it, the current situation is easy to identify, and if the layout is not needed it's easy to remove by adding `fluent-switch { margin: 0;}`. Certainly much less css than having to figure out exactly how much margin to put between controls, especially once variable density is in use. At this point I would prefer to wait until the variable density work is at least designed (hopefully soon) to make any changes there.

On a related note, I think the fast-field idea is great as it would clean up inconsistencies with label application currently. Without significantly restructuring these smaller controls we're discussing though, I'm not sure how well it would work for them considering the label is often inline or to the right of the component, instead of something like text inputs that are frequently above or in a column to the left. If that addition is anticipated soon I can start specing out designs for it as part of the density work.

**Comment by chrisdholt** [comment]
I mentioned above, but as there is already a visual refresh happening in FAST I think it's fine to do there. In Fluent, I don't think we can just leave this and assume that it's expected or the right thing. Coming on the heels of the visual refresh, it makes more sense to me to treat these as bugs to be fixed rather than wait for some in-the-future breaking change. Similarly, I don't believe any of the fluent-react components include margin as it relates to other controls without being scoped to some context - the fix will help bring us further into alignment with what is expected.

I've been gathering requirements for a `fast-field` component and putting together an issue to track the creation of a spec. Happy to try and get that issue up early this week.

**Comment by chrisdholt** [comment]
@eljefe223 Did this end up getting closed out or did we have more work to do on it? I don't recall if this was fully resolved or not.

**Comment by eljefe223** [comment]
@chrisdholt I believe we only addressed fluent elements and this remained open.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
