### ISSUE TITLE
feat: add menu button links to the Menu component

### ISSUE THREAD

**Issue by AndrewCraswell** [microsoft/fast#5415]
# 🙋 Feature Request

Menus currently can render `menuitem`, `menuitemradio`, `menuitemcheckbox`. But an important missing scenario are menu links. From the W3C examples, this occurs when the child element is an `anchor` with the `role` as `menuitem`.
https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

## 🤔 Expected Behavior

It should be possible to render hyperlinks as menu items.

## 😯 Current Behavior

The custom component itself is given the `role` attribute, meaning that a child `anchor` tag could not use the `menuitem` `role` designation.

## 💁 Possible Solution

Either create a new `menuitemlink` which inherits from the `anchor` tag or create a new prop on the `menuitem` component which renders the content inside an anchor tag.

## 💻 Examples

https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

**Comment by chrisdholt** [comment]
Just a note that I believe Anchors with a role of ‘menu item’ should be accepted as children - we filter in menu for the role. @AndrewCraswell is the issue here functionality related (they don’t functionally work as expected) or that they don’t visually work/look as expected? I believe that menu should allow for this scenario but I think the styling is a gap for sure. Thanks for the issue!

**Comment by chrisdholt** [comment]
Thinking through this - I think there are a couple of different ways we could handle this.

1) Enhance the `menu-item` template to support an optional href and anchor - this keeps things tidy from a naming approach as it's still a menu item, but it bloats out the template and we'd have to handle two interfaces to ensure that anchors could support all HTML anchor attributes. Not a fan of this approach due to the downsides of an unclear API.

2) Add a `fast-menu-item-link` or `fast-menu-link` component which extends anchor from a Foundational standpoint but provides a custom template with a role of `menuitem`. One delta here to be aware of is that I don't think this approach would support nested items. Besides that one could then use this in scenarios where an anchor is necessary or desired.

I'm leaning towards 2 above as I think it's a cleaner approach, but curious if others have thoughts or alternatives.

**Comment by scomea** [comment]
This markup seems to work aside from styling:

`<fast-menu>
    <fast-anchor href="https://microsoft.com" target="_blank" role="menuitem" style="display: block;">Anchor 1</fast-anchor>
    <fast-anchor href="https://microsoft.com" target="_blank" role="menuitem" style="display: block;">Anchor 2</fast-anchor>
    <fast-anchor href="https://microsoft.com" target="_blank" role="menuitem" style="display: block;">Anchor 3</fast-anchor>
</fast-menu>
`

![image](https://user-images.githubusercontent.com/7649425/143320129-dadbe8a6-8104-45df-88a5-3eed84547b1b.png)

**Comment by AndrewCraswell** [comment]
And it looks like the HTML structure puts the `role="menuitem"` on the correct element, so I think this works.

![image](https://user-images.githubusercontent.com/1908292/143673398-22deaf54-6a1e-4460-8b91-f5011dfe36ac.png)

**Comment by bheston** [comment]
Option 2 sounds right to me as well, assuming multiple inheritance isn't possible. The anchor template has an unfortunate number of attributes, but I don't believe we have any way around that now. It would be cool if we could centrally compose those in somehow, like adding an `aria` treatment to the element or something, but aside from that a plain copy and paste doesn't seem too painful at this point.

**Comment by scomea** [comment]
> And it looks like the HTML structure puts the `role="menuitem"` on the correct element, so I think this works.
> 
> ![image](https://user-images.githubusercontent.com/1908292/143673398-22deaf54-6a1e-4460-8b91-f5011dfe36ac.png)

I don't think you need the tabindex settings

**Comment by chrisdholt** [comment]
> > And it looks like the HTML structure puts the `role="menuitem"` on the correct element, so I think this works.
> > ![image](https://user-images.githubusercontent.com/1908292/143673398-22deaf54-6a1e-4460-8b91-f5011dfe36ac.png)
> 
> I don't think you need the tabindex settings

Yeah, and I think there is a styling story here that needs to be accommodated / aligned. This is certainly an option but I think first-class support for a simple element wouldn't be too bad either.

> Option 2 sounds right to me as well, assuming multiple inheritance isn't possible. The anchor template has an unfortunate number of attributes, but I don't believe we have any way around that now. It would be cool if we could centrally compose those in somehow, like adding an `aria` treatment to the element or something, but aside from that a plain copy and paste doesn't seem too painful at this point.

Yeah, I think the primary pain point here with reuse is that the element where focus is delegated needs to get the `role="menuitem"` attribute, so I'm not sure there is a good way to do that with full reuse. With that said, I have a local branch with a draft that I can push up this week hopefully.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
