### ISSUE TITLE
rfc: replace usage of Foundation button with HTML button in `search` template

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast#5451]
# 💬 RFC

In exploring the current search component and looking at styling beyond the walls of FAST, I'm finding that there are some significant negative implications to baking the Foundation button (using `context.tagFor(Button)`) into the template for the clear button. When building templates in FAST, we aim to either align to an existing template proposal from Open UI, or where there is not one, such as in the case of search - create a template that provides maximum flexibility. While the current code works with our conventions and leverages parts of the system, below I'll outline some of the potential issues and drawbacks I see with this implementation and why I believe that an HTML button or other element is likely a better solution for what is needed.

## 🔦 Context

1. In the case of the "clear text" button, the button itself does not receive focus (similar to input[type="search"]), do we need everything button brings to the table here?
2. By baking the foundation button into the template we add a shadowed dependency which deepens reliance on other FAST components. If I want to simply create a "search" component and publish it to NPM I now *must* create a Button as well in order to do so OR I must fork the template. While not the end of the world, our components become more tightly coupled with patterns like this. In some cases, such as that of Anchored Region it seems reasonable to add this layer because that provides necessary utility in the absence of an equal platform utility. In this case, I'm not sure we get any added benefit by using Button here.
3. We are really only using one appearance for the clear button, but we're taking the full class and all it's configuration where none is necessary. In the case of the implementation, it seems we also have to reset the context for the recipes in order to get them to work as expected. Would it be better to simply apply the expected values and/or recipes to a native element?

## Proposal

I'd propose we make a change to the clear button. I see two options:

1) Breaking Change - We break the template and move to using a native button element or even a span as we don't need the element to receive focus to achieve parity with the platform and retain a11y.

2) We enhance the template - We could enhance the template by moving this to be slotted content. While the template changes here still, it now allows configuration and the change would be transparent for `fast-components`. This feels more like a feature IMO but still breaking to an extent.

**Comment by bheston** [comment]
My thoughts are that the components should be built for systematized composition. While the individual components each represent a lot of decisions that went into making them as flexible and comprehensive as possible, their biggest benefit comes when they are used together.

Consistent styling and interaction are difficult, and the least number of sources of truth is one of the main ways we can address that.

In this case, the default configuration uses only one appearance, but someone else might want to change this to the `neutral` appearance, including whatever version of _their_ appearance that is, like:
![image](https://user-images.githubusercontent.com/47367562/145479661-1ff3f06d-a6e8-48ba-acd7-477ce86105ab.png)
If this is a native `button` or `span` this is one more place they would need to touch. I see this becoming more important as we bring in more adaptive systems.

It may not matter much for this button, but other components have good examples where a similar consideration might be made. You’ve already mentioned Anchored Region, and this probably implies there is no one-size-fits-all approach on either direction of the composition scale.

Regarding recipe usage in Context #3 above, this is true regardless, which is why I’ve wanted to fix it for so long. A comparable example is the expand/collapse button in Tree View Item. Because the `fillColor` context isn’t updated when an Item is hovered, we need to calculate what those colors would be if they were in the context of the Item hover color. Those buttons are div elements now, but if they were Buttons this would be automatic _if_ the context were also set. We get away with this so much because most colors are so close that visual perception is equivalent. This would fail on things like hint text over a hover background or stealth appearance where a backplate becomes obvious that it shouldn’t be there.

## Proposal

I lean toward leaving this as-is since it doesn’t appear it has come up during usage. Agreed the full Button is too much, and probably the best solution is a more robust way to apply combinations of styling so a native `button` or `span` would always match and be in sync with a styled Button component. Still on my wish list.

Otherwise, option 2 seems strongest to me because it allows the system to work when the whole framework is used, while allowing someone to pick and choose and customize as necessary. I suspect in that method we would add the Button to the `options` the same way we inject the Flippers into Horizontal Scroll. The downside of this approach is it requires a bit of manual syncing, like hooking up the classes, tab index, and click handler. I’m not sure what improvements we could make (if any) in this area, but that’s another reason I lean toward not separating them. This would also mean coming up with a way to handle the `close-glyph` slot, which I suspect means that becomes a `fast-components` interface, not `fast-foundation`.

**Comment by chrisdholt** [comment]
> My thoughts are that the components should be built for systematized composition. While the individual components each represent a lot of decisions that went into making them as flexible and comprehensive as possible, their biggest benefit comes when they are used together.

I appreciate this, but I think we are convoluting OUR implementations with the *intent* of Foundation. Foundation is intended to solve WEB problems, not OUR problems. We leverage it, but the intent is to provide a base template and class which can be used by _anyone_ for a number of scenarios. We need to really, really be considering far more than just our own needs and our own visuals when we are building out Foundation. If we don't, we are going to make poor assumptions that make it harder for this to be used in the way it's intended - to solve problems for the broader web community.

> Consistent styling and interaction are difficult, and the least number of sources of truth is one of the main ways we can address that.

Again, this argument seems directed at our visual implementation, we should be looking across many possible use cases. What this specific pairing introduces is a direct relationship between the *clear* button on Search and the core "Button" component - the button which is registered for ANY given design system. What this assumes is that all instances of search work with a design systems "Button" implementation. While that may be the case for our system, I don't think that assumption can be made.

> In this case, the default configuration uses only one appearance, but someone else might want to change this to the `neutral` appearance, including whatever version of _their_ appearance that is, like: ![image](https://user-images.githubusercontent.com/47367562/145479661-1ff3f06d-a6e8-48ba-acd7-477ce86105ab.png) If this is a native `button` or `span` this is one more place they would need to touch. I see this becoming more important as we bring in more adaptive systems.

Yeah and in this case I think that really comes down to implementation. The slot enables someone to pass a neutral button and it provides a default use case for someone who _just_ wants to use search to write a simple shareable `search` component without needing to create additional controls to use it as is currently the case. While I think that DevEx is valuable, I think it's important to consider the separation of concerns here. If we want to provide more ergonomics we can definitely look into how to do that in `fast-components`, but I think it works against the goals and intent of the Foundation package if we start to convolute our approach with the broader communities use cases for it.

> It may not matter much for this button, but other components have good examples where a similar consideration might be made. You’ve already mentioned Anchored Region, and this probably implies there is no one-size-fits-all approach on either direction of the composition scale.

100% - We should be really careful here. The thing with anchored region is that it's more a utility needed at this point in time (until popup and anchored positioning come in the browser...hopefully soon!) to make certain experiences work. We could remove the abstraction and it would just be "the way" but that would mean duplication. I do think there are other scenarios where there are more common relationships and we can absolutely look at this approach - but we'll want to make sure it makes sense. In the case of this button I don't think we can assume that the primary button implementation will include an appearance which is used for the clear button, which is technically what the implementation ends up doing here. So in the example you give above of the neutral and round button, that would work only so long as you have that concept in the component registered as Button in the design system - a stretch for all or even most IMO.

> Regarding recipe usage in Context #3 above, this is true regardless, which is why I’ve wanted to fix it for so long. A comparable example is the expand/collapse button in Tree View Item. Because the `fillColor` context isn’t updated when an Item is hovered, we need to calculate what those colors would be if they were in the context of the Item hover color. Those buttons are div elements now, but if they were Buttons this would be automatic _if_ the context were also set. We get away with this so much because most colors are so close that visual perception is equivalent. This would fail on things like hint text over a hover background or stealth appearance where a backplate becomes obvious that it shouldn’t be there.

Yeah and I'll add that I think this point is really more about implementation details which again is kind of an "us" problem vs. a "Foundation" problem.

> ## Proposal
> I lean toward leaving this as-is since it doesn’t appear it has come up during usage. Agreed the full Button is too much, and probably the best solution is a more robust way to apply combinations of styling so a native `button` or `span` would always match and be in sync with a styled Button component. Still on my wish list.

This feels like an argument for our implementation and not Foundation - again, that's totally doable but I would push back that the constructs being brought up are specific to our implementation of Foundation.

> Otherwise, option 2 seems strongest to me because it allows the system to work when the whole framework is used, while allowing someone to pick and choose and customize as necessary. I suspect in that method we would add the Button to the `options` the same way we inject the Flippers into Horizontal Scroll. The downside of this approach is it requires a bit of manual syncing, like hooking up the classes, tab index, and click handler. I’m not sure what improvements we could make (if any) in this area, but that’s another reason I lean toward not separating them. This would also mean coming up with a way to handle the `close-glyph` slot, which I suspect means that becomes a `fast-components` interface, not `fast-foundation`.

Well, in the case of this I don't think we need to hook much up except a click handler. There isn't really a ton of manual syncing and we technically could include include a button in the template by default and handle that click behavior. In the case of passing in a custom button to that slot, the primary work is visual styling which you're already doing if you are implementing Foundation. Similarly if you are wiring in a custom button, say like we might want to do in FAST components, we're going to be managing that stuff ourselves. As with the other notes above, when it comes to foundation the primary concern we should have for styling should be whether or not our template can be used by a variety of visual systems to accomplish a majority of use cases. Over time the goal should be to move more and more towards platform elements, especially as we work to improve their structure and composability through the Open UI effort.

**Comment by rajsite** [comment]
> Well, in the case of this I don't think we need to hook much up except a click handler.

Out of curiosity for a button like the following (a button that has to be clicked twice to activate):

![az5button](https://user-images.githubusercontent.com/1588923/148133926-822fa5ec-b056-4520-aeaa-632a643684c9.gif)

It would participate as a slotted element by using preventDefault on the first click and only allowing through the activation click? A more esoteric control would have to simulate a click event?

If the search component was in a disabled state would it set the disabled attribute on the slotted element (say it has a custom disabled style)? Or maybe controls need to be designed with that in mind and use something like host-context (not in safari)?
```css
:host-context([disabled]) { /* custom disabled style*/ }
```

**Comment by eljefe223** [comment]
Fixed by: #5464
