### ISSUE TITLE
feat: add DirectionalStyleSheetBehavior to fast foundation

### ISSUE THREAD

**Issue by rajsite** [microsoft/fast#5547]
# 🙋 Feature Request

In a design system built on fast foundation (but not using fast component design tokens) we want to be ltr/rtl aware.

In order to do that we ended up copying and pasting  [`direction.ts`](https://github.com/microsoft/fast/blob/7fd3f17ae4a54c44605b82915e355423833a8c1c/packages/web-components/fast-components/src/styles/direction.ts) with the only modification being to provide our own Direction DesignToken implementation.

What's interesting is that both the fast component's direction design token and our direction design token use the same [Direction enum from `@microsoft/fast-web-utilities](https://github.com/microsoft/fast/blob/7fd3f17ae4a54c44605b82915e355423833a8c1c/packages/utilities/fast-web-utilities/src/localization.ts).

I think localization would (should?) be a common feature for many design systems. I'd like to leverage [fast's patterns for localization](https://github.com/microsoft/fast/blob/7fd3f17ae4a54c44605b82915e355423833a8c1c/packages/web-components/fast-components/docs/design/localization.md) in design systems built on fast foundation. 

## 🤔 Expected Behavior

Be able to create the DirectionStyleSheetBehavior using my own design tokens and decoupled from fast component design tokens.

## 😯 Current Behavior

Have to duplicate DirectionStyleSheetBehavior for my own application and update it to use my DesignToken. Becomes something I maintain myself and is not readily available for all fast foundation-based design system implementations.

## 💁 Possible Solution

See above.

## 🔦 Context

Found that a component in our design system had mistakenly imported DirectionStyleSheetBehavior which caused all the fast component design tokens to be defined (but unused) and added an unexpected dependency to fast components.

## 💻 Examples

N/A

**Comment by rajsite** [comment]
Do y'all know the relationship between [DirectionStyleSheetBehavior](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-components/src/styles/direction.ts) and usage of [getDirection](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/utilities/direction.ts)?

It seems like there must be a connection between the html attribute being set in the DOM and the direction design token for them to be in sync but I'm not seeing it.

**Comment by bheston** [comment]
This has been an issue for a while now. Hopefully it will be an easy fix to pair them ,or perhaps defer to the html attribute since that's built into the platform. The design token pairs with the previous design system implementation, but we may not need to carry that forward if there's a more consistent way.
Let's prioritize fixing this if we can. It will come up in other areas soon I believe.

**Comment by janechu** [comment]
I believe this has been moved to [fluent ui web components](https://github.com/microsoft/fluentui/tree/master/packages/web-components), since `@microsoft/fast-components` and `@microsoft/fast-foundation` is in process of being deprecated you may want to take a dependency on that package, or copy the logic into your project.
