### ISSUE TITLE
feat: expose stylesheet content from ElementStyles

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5594]
The `fast-ssr` package needs to be able to emit stylesheet content into the SSR output, which means it needs access to the content from each `ElementStyles` instance. `ElementStyles` should expose a mechanism to read this style information, such as:

```ts
abstract class ElementStyles {
    // ...
    readonly public content: string; // content of the CSSStyleSheet / HTMLStyleElement
}
```

**Comment by EisenbergEffect** [comment]
Since `ElementStyles` can actually encapsulate more than one style sheet, I was thinking we probably want to provide a `string[]`. This would let the renderer optimize by keeping a hash of the styles that it has already seen so it can use the `fast-style` element. My proposal is the following API:

```
abstract class ElementStyles {
    // ...
    getCSS(): string[];
}
```

I would throw a not supported error for the adopted style sheet version since I don't think we can get the strings back and it's not needed for SSR.

Thoughts?
