### ISSUE TITLE
ViewTemplate.html is incompatible with SSR TemplateRenderer

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5618]
Today, `ViewTemplate.html` is typed as a `string | HTMLTemplateElement`. This presents a failure opportunity for SSR parsing code, because the parsing code is designed to work from string templates, not from an HTMLElement implementation.

Until we come to a conclusion on this the `TemplateRenderer` will simply throw if it encounters anything but a string when reading the `ViewTemplate.html` property, but we should resolve on a strategy for that scenario here.

**UPDATE**

After some discussion, we've decided to leave the API as is so that we can support special client-only scenarios for `HTMLTemplateElement`. The SSR implementation will explicitly not support this and will throw.

Follow-up tasks to unblock the template renderer include:

* [x] #5639
* [x] #5638

**Comment by EisenbergEffect** [comment]
I've been thinking about this while working on the pluggable style strategy system.I think we might want to take a similar approach here...

Technically, `AdoptedStyleSheetsStrategy` works with `string` or `CSSStyleSheet` instances, which we won't have in SSR. The template engine is pretty similar in that it works with either `string` or `HTMLTemplateElement` instances. For CSS we'd have to only allow using strings when writing code that runs universally on server and client, and so I think we can make the same restriction for templates. However, I'd like to leave both APIs open for non-string inputs for special client-only scenarios.

I'm wondering if we can implement a similar strategy pattern for templates that enables SSR to plug in its own compiler. The SSR version would just accept strings and throw in any other case.

@nicholasrice When you get a chance, I'd like to sync up on how you are working with/around the current template and compiler code so that I can see if there's a way to enable this same type of strategy pattern.
