### ISSUE TITLE
feat: create API to retrieve the final template and styles for a component

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#5638]
Right now there's no way to get the template or the styles that a web component is rendering with, based on all resolution logic. Expose this through an official API so that SSR can use it to render on the server.

**Comment by nicholasrice** [comment]
I think we may need to re-approach the solution for getting component stylesheets for SSR rendering. This approach we implemented does not expose any stylesheets added via `Controller.addStyles()` calls. This is a problem because the `PropertyStylesheetBehavior`, for example, is a behavior that conditionally adds a stylesheet when a property of an element matches some value. We use this to conditionally add appearance stylesheets for buttons and anchors. Because `Controller.styles` does not expose those conditional styles, it's impossible (AFAIK) to emit those sheets in SSR environments.

**Comment by EisenbergEffect** [comment]
If we added something like`getAllStyles()` to controller that was an iterator and returned the sore resolved styles plus all the styles held by the controller, would that work?

**Comment by nicholasrice** [comment]
Yep. SSR just needs a mechanism to retrieve *all* styles applied to an element.

**Comment by nicholasrice** [comment]
@EisenbergEffect scratch that! I just realized I can use the SSR style strategy to track that info and implement a retrieval mechanism directly in the SSR package. No work from you needed!
