### ISSUE TITLE
rfc: add prefixes to generic class names

### ISSUE THREAD

**Issue by claviska** [microsoft/fast#5644]
# 💬 RFC

We've adopted a number of FAST Foundation components and the use of generic classes that are conditionally added to the host element, [such as required form controls](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/src/form-associated/form-associated.ts#L443-L450), are conflicting with consumer styles.

In the case of `required`, for example, our consumers have a longstanding practice of using the following to append an asterisk to their required form controls.

```css
.required:after { 
  content: "*"; 
  padding-left: 2px;
} 
```

While I agree their selector is too generic and this isn't technically a FAST issue, it's an unfortunately common practice.

I wanted to start a discussion to see how the maintainers and community feels about prefixing classes like this — or omitting them altogether since the attributes usually reflect.

For prefixing, using `fast-` as a namespace would be reasonable. In the case of DSPs, using the tag's prefix would also be acceptable.

Thoughts?

**Comment by chrisdholt** [comment]
Thanks for filing this @claviska. Our approach thus far has been to style host elements with the attribute (due to potential clobbering when used within *React*). I think our intent of providing the classes rather than attributes was to provide a class selector for folks to hook into, though without that documented this issue is bound to happen. I think the rub here is likely with things which aren't reflected and represented as attributes which exist as classes only (thinking of `indeterminate` as an example) - and I'm not sure we have a good/better way of handling that currently. For things which are reflected, we certainly could omit them.

I think prefixing is something we can look at enabling which could be done in a backwards compatible way. I think we have a similar desire to allow "opt-in" of prefixing the CSS Custom properties from a design system. I think the quickest way to land resolution on this without a breaking change would be to enable "opt-in" of prefixing of classes using the design system prefix. @EisenbergEffect do you have thoughts on potential pitfalls of this as it relates to the foundation templates?

The alternative would be to always prefix these with a generic and not-customized prefix, but in order to make that shift we'd likely need to wait to make a breaking change, which is still a few months out I believe (related to FAST Element 2.0).

**Comment by EisenbergEffect** [comment]
I thought we had eliminated most cases of classes being added to host elements. I think it would be good to first do a survey of all the places where that is still happening, remove the ones that can be handled with an alternative approach, and then see what we're left with. Maybe the ones that are left don't matter that much? e.g. `indeterminate`

I think that most of what would be left after the above would be a candidate for CSS custom pseudo selectors, but those haven't landed yet. So, we need some other approach. We'd have to look at what cases where left after the cleanup and see what patterns emerged. Classes are an easy choice if we can't accomplish what we want with an attribute. We could prefix these classes. Maybe using a more semantic prefix instead of something like "fast" would be better? Again, we probably need to see what patterns are left.

We've talked about enabling optional prefixing of CSS variables through configuration. Prefixing the class names would be tricky if we want that to be configurable. I'm not sure how we'd get that configuration data piped through to the component class instance in a performant way. For that reason, I'd prefer to avoid classes as much as possible and then if we can't, prefix them with a non-configured prefix.

**Comment by chrisdholt** [comment]
I just did a run through on this and we've removed the indeterminate scenario and I'm pushing a PR to remove a residual class name. Also looking forward to CSS pseudo selectors for states, etc.

Given that host elements no longer have classes and any other classes existing on the templates are scoped within a given component template, I'm going to close this as "completed", albeit "obsolete" at this point. Thanks for the issue @claviska, we're in a better spot for it :)
