### ISSUE TITLE
feat: add aria-description attribute to textarea/text-field elements

### ISSUE THREAD

**Issue by simonxabris** [microsoft/fast#5655]
# 🙋 Feature Request

I want to be able to set the `aria-description` attribute on a textfield or a textarea in an idiomatic way like
```ts
this.ariaDescription = 'some description';
```

## 🤔 Expected Behavior

There's an `ariaDescription` property exposed on these form elements which sets the correspondig aria attribute on the `control` element.

## 😯 Current Behavior

Currently a lot of aria attributes are exposed this way with the `ARIAGlobalStatesAndProperties` class, but not `aria-description`. This leads to having to do workarounds like
```ts
this.control.setAttribute('aria-description', 'some description');
```

which works, but I feel like it's not the idiomatic FAST way of doing this.

## 💁 Possible Solution

The `ariaDescription` property is added to the `ARIAGlobalStatesAndProperties` class, then it would get automatically exposed on textfield and textarea elements since this class is applied as a mixin to those.

## 🔦 Context

The reason I'm requesting this feature is I'm creating a `textarea` element for our design system and we want the user to be able to provide helper text element displayed at the bottom of the input. They will be able to provide this element via a `helpertext` slot which we append into the `FoundationTextArea` element's template in a `connectedCallback`. To make this accessible, I need to set the slotted helper text elements `textContent` as the `aria-description` attribute's value on the actual input. `aria-describedby` does not work in this scenario, because the `id` of the slotted element does not penetrate the shadow-dom.

I'd be happy to submit a PR with the appropriate changes if you think this should be added, also if you need any further input or clarification I'm happy to help as much as I can!

**Comment by chrisdholt** [comment]
Thanks for the issue @simonxabris. I'm currently leaning towards holding off on adding this at this point, but I'm going to mark this as under consideration for now as I think there's some things to consider beyond this specific request. The `ARIAGlobalStatesAndProperties` mixin is based on what exists on the interface from TypeScript which I believe typically tries to add things which basically have consensus (the Paint Worklet API's weren't in as of 4.3.5). It looks like this is fairly new and neither Firefox or Safari support it as of yet. I think in order to add this we'd need to decide on a policy of our own rather than mapping to TypeScipts ARIAMixin.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-components` has been deprecated for some time.
