### ISSUE TITLE
fix: ADA Compliance nested interactive control issue in fast-accordion and loading-button components

### ISSUE THREAD

**Issue by maraah1** [microsoft/fast#5700]
# 🐛 Bug Report

Fast-accordion buttons are throwing an error during fast pass accessibility testing. There is no clear text for screen reader to pick up on within the component:

![Web capture_2-3-2022_12331_ghbhpcookfemncgoinjblecnilppimih](https://user-images.githubusercontent.com/34525412/156611140-31ce21e8-9176-466f-bec7-4dc8c8320c14.jpeg)

## 💻 Repro or Code Sample

Imported the fast-accordion component:

<img width="507" alt="Screenshot 2022-03-03 105356" src="https://user-images.githubusercontent.com/34525412/156612672-7f972ebe-38fd-4d0b-bbba-a9e1cd8f844b.png"> 

## 🤔 Expected Behavior

No accessibility errors like the screenshot shown above

## 😯 Current Behavior

![Web capture_2-3-2022_12331_ghbhpcookfemncgoinjblecnilppimih](https://user-images.githubusercontent.com/34525412/156612971-9fc2ebdd-0e01-4749-ac34-af741fa519d8.jpeg)

## 💁 Possible Solution

This is the solution given by the accessibility team: https://dequeuniversity.com/rules/axe/4.3/nested-interactive?application=msftAI

## 🔦 Context

We are working to accomplish our site being ADA Compliance approved and to pass the accessibility tests so the site is useable for everyone.

## 🌍 Your Environment

* OS & Device: Windows
* Browser  Microsoft Edge
* Version 98.0.1108.62

**Comment by chrisdholt** [comment]
After looking at your code snippet provided above, I believe that the error noted here exists in your implementation. The error seems to be noting that focusable relents are being passed into the heading, which is a button. In looking at your template, you indeed are passing a button into the heading itself. Happy to provide feedback on how you may be able to accomplish your UI error free, but the error here is due to issues introduced by your implementation as the entire heading is and by the spec, should be wrapped within a button.

**Comment by maraah1** [comment]
Thanks for looking into it! So you're suggesting that the component should be wrapped in a button? @chrisdholt

**Comment by chrisdholt** [comment]
@maraah1 one more helpful link that I forgot - the relevant portion of the spec detailing why the header is enclosed within a button: https://w3c.github.io/aria-practices/#wai-aria-roles-states-and-properties

**Comment by maraah1** [comment]
@chrisdholt Thanks it worked when I used a different way to display the icon other than using flipper-button!
