### ISSUE TITLE
feat: restrict DesignToken to being set for FASTElement instances only

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast#5902]
# 🙋 Feature Request
DesignToken can currently be set and retrieved for any HTMLElement instance, and this poses two problems. The first is that native elements cannot be reliably watched for DOM detachment, which should force DesignTokens to re-evaluate.  This can lead to odd behavior, where tokens resolve from an element that is no longer in the DOM. Second, SSR infrastrucutre only constructs custom elements, it does not construct native HTMLElements. This means that any tokens set for native elements in a shadow DOM will not be evaluated, potentially causing rendering deltas between SSR and client rendered elements.

I'd like to limit the elements for which DesignTokens can be set to FASTElement instances. This will ensure that the token graph can always be reconciled w/ element attachment state and that SSR infrastructure can achieve render parity with client code.

To achieve feature-parity in components, it is likely that https://github.com/microsoft/fast/issues/5286 would also need to be done for this work, because there are a few cases in components where tokens are being set for native elements in component shadow DOMs.

**Comment by chrisdholt** [comment]
@nicholasrice does this include not supporting the current behavior for `document.body` or would that be a special non-FE case we support?

**Comment by nicholasrice** [comment]
The `withDefault()` would still reflect to the `document.body`, but `token.setValueFor(document.body, value)` would not be supported due to the type signature change.

**Comment by bheston** [comment]
I was initially concerned about this, but after our chat I see it's not much different than what we have today. The only issue I see with this is one we have already today as described in #5848. We have discussed solutions to that, which once resolved will apply identically given the change proposed here.

From the perspective of the color system, the best example of how this might be an issue is anywhere a non-component is nested within a component that might need to have its own context. Specifically, this is seen is the expand/collapse button in a Tree View Item. The item itself has a backplate, which in many designs responds to hover and active state by changing color. If the expand/collapse button within derives its color from the current item state color, if that button is not a nested component it will require manual evaluation of the correct color for each state.

Building on the structure of the tree item described above, a simpler example of where this might be an issue is if someone wants to have different corner radius for the item and the button. If they were both styled to use the same corner radius token, there would be no easy way to adjust the radius for the inner button because it would not be valid to apply an update to the design token there.

I think there are solutions to this with the work I'm doing around applying style decisions in the future. the benefits of solving this seem to outweigh any limitations it might introduce for now.
