### ISSUE TITLE
Styling issue with the checkbox component.

### ISSUE THREAD

**Issue by apanwar22i** [microsoft/fast#6203]
I followed the steps from the given tutorial
https://docs.microsoft.com/en-us/fluent-ui/web-components/components/checkbox

I used the checkbox tag like this
![image](https://user-images.githubusercontent.com/109206668/178686249-4c17609d-db48-4b23-8dc2-026271d9eba2.png)

But giving me the result like that:
![image](https://user-images.githubusercontent.com/109206668/178686025-3c11422b-fa9d-4f90-8796-f5d9ce87f4d5.png)

**Comment by KingOfTac** [comment]
Stackblitz using the latest `fluentui/web-components` and `fast-react-wrapper` with a `fluent-checkbox` https://stackblitz.com/edit/react-ts-wr3hj1?file=App.tsx

**Comment by EisenbergEffect** [comment]
@apanwar22i Can you confirm that this fixes your issue?

**Comment by apanwar22i** [comment]
@EisenbergEffect not yet, however, we have got a workaround suggested with https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1772, and we are trying that now. I will update once it works.

**Comment by apanwar22i** [comment]
@EisenbergEffect @KingOfTac We tried a solution which was given inside this ticket https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1772

**Comment by EisenbergEffect** [comment]
Ok, closing this one out. The root of the issue seems to be that MGT isn't running the latest version of the Fluent components and that is causing some mis-matches in the styles. There's a work around in place and from some conversations we've had internally, MGT plans on updating the libraries to address this longer term as well.
