### ISSUE TITLE
fix: FAST components bleed through `table` headers

### ISSUE THREAD

**Issue by atmgrifter00** [microsoft/fast#6395]
# 🐛 Bug Report

If you provide FAST components as the cell element inside a `<td>` element, and then make the `<th>` elements stick through using the CSS `position: sticky;` setting, if you then scroll the contents of a table the FAST components will render on top of the `<th>` content. Standard HTML components do not exhibit this issue.

## 💻 Repro or Code Sample

See [this Stackblitz example](https://stackblitz.com/edit/angular-ivy-1sjjfg?file=src/app/app.component.css). Note that it being an Angular app has nothing to do with the problem.

~~You'll see in the example app some commented out CSS that is an attempt at mitigating the problem, but it's not perfect, and it's unclear if there are other, more complete workarounds that would provide the expected behavior. Note that even if there were a perfect workaround, I don't believe that means the issue would be resolved.~~

It appears that giving the `<th>` tags a z-index of 1 resolves the problem. This might be sufficient for our purposes.

## 🤔 Expected Behavior

If you scroll the table contents, the `<th>` content should always render on top of the `<td>` content.

## 😯 Current Behavior

As you scroll the table contents, the FAST component renders on top of the header, while the other cells do not.

![FASTtable_bug](https://user-images.githubusercontent.com/26874831/191847051-c62653bc-436f-4800-96a0-d84097d1487c.gif)

## 💁 Possible Solution

As mentioned above, setting the z-index to 1 for the `<th>` elements seems to resolve the problem. So while not an explanation for why FAST components behave the way they do without that, it seems a pretty painless workaround.

## 🔦 Context

This is an impediment to us developing a custom table element that supports FAST elements as templated content for cells.

**Comment by chrisdholt** [comment]
I’m not able to investigate immediately, but y his appears to be an issue with CSS stacking context which should be resolvable with CSS. Without investigating I can’t comment which component exhibits the issues or why, but the reason native elements don’t have this issue is that they don’t have any CSS from user land.

**Comment by EisenbergEffect** [comment]
I'm going to close this out since it's not necessarily a FAST issue. As @chrisdholt points out, it's likely related to stacking context or just document order. You can solve the problem by adding a z-index to your table header. I think this practice is probably pretty common when using `position: sticky`.
