### ISSUE TITLE
feat: upgrade to Docusaurus 2.0

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#6416]
# 🙋 Feature Request

Docusaurus 2.0 is now stable: https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0

We're currently locked to `2.0.0-beta.20` in the `fast-site` package (`sites/website`).

**Comment by EisenbergEffect** [comment]
I wonder if @huynhicode would be interested in a little OSS contribution to help us out with this 😉

**Comment by huynhicode** [comment]
Yes, I would love to!  Thanks for thinking of me @EisenbergEffect .

**Comment by EisenbergEffect** [comment]
Wondrously wonderful! These sorts of contributions really help us out. @huynhicode I'm not sure if you remember, but I had to change up the cards on the docs intro because there was an issue with the links. It might be cool to see if the bug was fixed and we could re-enable that after updating.  It was kid of tricky to test though...

**Comment by huynhicode** [comment]
I will take a look!

**Comment by janechu** [comment]
Update to v3 has been completed with #6947.
