### ISSUE TITLE
docs: There should be only one installation guide/npm package for Vue.js

### ISSUE THREAD

**Issue by OneWorld123** [microsoft/fast#6514]
# 🙋 Documentation Request

I want to integrate the look and feel of FluentUI into a Vue.js app. 

* [FAST website tells me use `@microsoft/fast-components`](https://www.fast.design/docs/integrations/vue/)
* [The readme of this git repo and the Microsoft page tells me to use `@fluentui/web-components`](https://learn.microsoft.com/en-us/fluent-ui/web-components/integrations/vue)

Why are there two solutions provided for the same thing? 

## 💁 Possible Solution

* Offer some explanation, why and when to use `@microsoft/fast-components` over `@fluentui/web-components` for Vue.js on the [installation guide](https://www.fast.design/docs/integrations/vue/).
* Otherwise [this](https://www.fast.design/docs/integrations/vue/) installation guide should not exist. Instead, it should point to https://learn.microsoft.com/en-us/fluent-ui/web-components/integrations/vue.

**Comment by EisenbergEffect** [comment]
@OneWorld123 We apologize for the confusion. These are actually not two solutions for the **_same_** thing. These are two completely different design systems.

FAST enables the creation of multiple design systems, in order to meet the broad needs of the industry. You can use FAST to create Fluent, Material, Lion, etc. with minimal effort. The official Fluent UI Web Components are built on FAST. We also used to support a second "starter" design system known as "fast-components".

If you want a highly configurable starter design system, then you would use `@microsoft/fast-components` as the base of your own design system. This is now deprecated and will be replaced with custom design system tooling in vNext. 

If you want the Fluent UI system specifically, and don't wish to create your own design system, then you would use `@fluentui/web-components`.

I'm going to close this issue for now since we are currently tracking/working on a plan to improve both the home page as well as the documentation, which should make this much less confusing in the future.
