### ISSUE TITLE
fix: label attribute value should be set as text in listbox option

### ISSUE THREAD

**Issue by yinonov** [microsoft/fast#6642]
# 🐛 Bug Report

setting label on `option` does not reflect to DOM

(notice option 2)

<img width="574" alt="image" src="https://user-images.githubusercontent.com/15140652/219020896-7369353a-c043-40dd-a24e-a8e76ab62dc6.png">

according to [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attr-label)

> `Label` attribute is text for the label indicating the meaning of the option. If the label attribute isn't defined, its value is that of the element text content.

## 🤔 Expected Behavior

label should precede html content

(see first option)

<img width="676" alt="image" src="https://user-images.githubusercontent.com/15140652/219021254-ed5fe305-7276-470b-92a6-66d12b176ded.png">

**Comment by chrisdholt** [comment]
This will be difficult because we would need to override what is being projected into the default slot. I'm not sure how we could/would do that. While it's doable for the native element, I'm not sure we have the same ability to do this with how projection works. I certainly understand the desire to stay close here, but I'm not sure it's reasonably feasible or intuitive for this scenario.

**Comment by yinonov** [comment]
how about visually hiding the default slot and extract its `textContent` to populate into the template?
or some manipulation utilizing the `slotted` directive with filter?

can this go south?

**Comment by chrisdholt** [comment]
@yinonov if you want to open a PR against the main branch I think we'd take something here as a contribution. I think you're on the stable release still which we can cherry-pick the change into.

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
